### PR TITLE
Migrate docs to VitePress.

### LINKED ISSUE #793: Migrate docs to `vitepress`
`mdbook` only supports file-level chapter names at the moment, but our chapters are pretty long so we'd like to show at least one level of subsections as well.  Unfortunately, anchors break `mdbook` at the moment.

Tracking https://github.com/rust-lang/mdBook/issues/167.

### PR DESCRIPTION
**Pull request by pkaminski**
Everything made it over except for our custom syntax highlighting colors.  There's no Color Brewer theme for [Shiki](https://github.com/shikijs/shiki) and I don't want to get bogged down with creating one.

Resolves #793.

- - -
This change is [Reviewable](https://reviewable.io/reviews/Reviewable/Reviewable/1185)

### CODE REVIEW

**Comment by pkaminski** [comment]
FYI @BlackVegetable

**Review by earlAchromatic — COMMENTED** [review]
This PR makes me so happy 🥹

> Reviewed 46 of 46 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Reviewable/Reviewable/1185#-:-O7AyeakEm9BlOIA6fLw:b-b8glsd)* status: all files reviewed, 3 unresolved discussions (waiting on @pkaminski)

*[a discussion](https://reviewable.io/reviews/Reviewable/Reviewable/1185#-O7AWI_P61MREnrUC_W5:-O7AWI_P61MREnrUC_W6:b-arot53) (no related file):*
Do we want to add Missive chat here as well at some point? I thought it was already on the docs but it's not!

___
___
*[`docs/tweaks.css` line 1 at r1](https://reviewable.io/reviews/Reviewable/Reviewable/1185#-O7B02Kg87tg4I_4B1Cs:-O7B02Kg87tg4I_4B1Ct:bgu7io9) ([raw file](https://github.com/Reviewable/Reviewable/blob/239e39cf05147677e84d2cec03f21a3d8326c259/docs/tweaks.css#L1)):*
> ```CSS
> // #region show-line-numbers
> ```

We'll have to update the code that parses this file in `experiments` too. I can do that if you want.
___
*[`.github/workflows/docs.yaml` line 21 at r1](https://reviewable.io/reviews/Reviewable/Reviewable/1185#-O7Az4ww0fLwO4mBr3dv:-O7Az4ww0fLwO4mBr3dw:b-z4hg03) ([raw file](https://github.com/Reviewable/Reviewable/blob/239e39cf05147677e84d2cec03f21a3d8326c259/.github/workflows/docs.yaml#L21)):*
> ```YAML
>       - name: Generate docs
>         working-directory: docs
>         run: yarn docs:build
> ```

Huh, I tried to build and got: `(!) Found dead link ./introduction in file SUMMARY.md`. Needs fixed before launch.
___
*[`docs/index.md` line 0 at r1](https://reviewable.io/reviews/Reviewable/Reviewable/1185#-O7B2EcKC0YMeiZPK6Rh:-O7B2EcKC0YMeiZPK6Ri:b-lvwbn) ([raw file](https://github.com/Reviewable/Reviewable/blob/239e39cf05147677e84d2cec03f21a3d8326c259/docs/index.md#L0)):*
Ah, this file got renamed from `introduction` -> `index` but `introduction` is referenced in `SUMMARY.md` and so gets caught as a dead link (that's why the build fails). I think we can get rid of the summary file anyways, right?

**Review by pkaminski — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Reviewable/Reviewable/1185)* status: 44 of 48 files reviewed, 3 unresolved discussions (waiting on @earlAchromatic)

*[a discussion](https://reviewable.io/reviews/Reviewable/Reviewable/1185#-O7AWI_P61MREnrUC_W5:-O7BBl6j34Lm2v3AtUhf:b3kpo0r) (no related file):*
<details><summary><i>Previously, earlAchromatic (Jacob Milhorn) wrote…</i></summary><blockquote>

Do we want to add Missive chat here as well at some point? I thought it was already on the docs but it's not!
</blockquote></details>

Sure, why not.  I don't want the button always showing in the corner, though, so I added a navbar item to open the chat, similar to how we do it through the support menu in the app.  (I reorganized the navbar while at it.)

___
___
*[`docs/tweaks.css` line 1 at r1](https://reviewable.io/reviews/Reviewable/Reviewable/1185#-O7B02Kg87tg4I_4B1Cs:-O7BAhxXCXzg15aoclZS:b-emnklo) ([raw file](https://github.com/Reviewable/Reviewable/blob/239e39cf05147677e84d2cec03f21a3d8326c259/docs/tweaks.css#L1)):*
<details><summary><i>Previously, earlAchromatic (Jacob Milhorn) wrote…</i></summary><blockquote>

We'll have to update the code that parses this file in `experiments` too. I can do that if you want.
</blockquote></details>

Oh, I completely forgot it was parsed elsewhere.  I'll take you up on your offer since I assume you can do it faster than me.
___
*[`.github/workflows/docs.yaml` line 21 at r1](https://reviewable.io/reviews/Reviewable/Reviewable/1185#-O7Az4ww0fLwO4mBr3dv:-O7BAcST9gtWix0Dbsdm:b-4hlltv) ([raw file](https://github.com/Reviewable/Reviewable/blob/239e39cf05147677e84d2cec03f21a3d8326c259/.github/workflows/docs.yaml#L21)):*
<details><summary><i>Previously, earlAchromatic (Jacob Milhorn) wrote…</i></summary><blockquote>

Huh, I tried to build and got: `(!) Found dead link ./introduction in file SUMMARY.md`. Needs fixed before launch.
</blockquote></details>

Ah, I forgot to delete that file.  Done.

**Review by earlAchromatic — COMMENTED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Reviewable/Reviewable/1185)* status: all files reviewed, 1 unresolved discussion (waiting on @pkaminski)

___
*[`docs/.vitepress/components/Missive.vue` line 36 at r2](https://reviewable.io/reviews/Reviewable/Reviewable/1185#-O7BZbk91XQVMa62KZPT:-O7BZbk91XQVMa62KZPU:b-lstdnd) ([raw file](https://github.com/Reviewable/Reviewable/blob/c6a5879ff9095357e3e673b804a430b1835ab53e/docs/.vitepress/components/Missive.vue#L36)):*
> ```Vue
> let opened = false;
> 
> const observer = new MutationObserver(mutations => {
> ```

I think you need to wrap all this stuff in the `onMounted` or the SSR will break.

**Review by pkaminski — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Reviewable/Reviewable/1185)* status: 47 of 48 files reviewed, 1 unresolved discussion (waiting on @earlAchromatic)

___
*[`docs/.vitepress/components/Missive.vue` line 36 at r2](https://reviewable.io/reviews/Reviewable/Reviewable/1185#-O7BZbk91XQVMa62KZPT:-O7BucMu8KfkO-y9Ld4M:b-896fix) ([raw file](https://github.com/Reviewable/Reviewable/blob/c6a5879ff9095357e3e673b804a430b1835ab53e/docs/.vitepress/components/Missive.vue#L36)):*
<details><summary><i>Previously, earlAchromatic (Jacob Milhorn) wrote…</i></summary><blockquote>

I think you need to wrap all this stuff in the `onMounted` or the SSR will break.
</blockquote></details>

Done.

**Review by earlAchromatic — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Reviewable/Reviewable/1185#-:-O7C-M3EBwrtsWhXOjQu:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @pkaminski)

**Pull request merged**
