### PR TITLE
Update documentation and changelog.md for disabled connections

### PR DESCRIPTION
**Pull request by snoack**
This PR adds documentation for [disabled connections](https://github.com/Reviewable/reviewable-server/issues/244), and adds it to changelog.md.

- - -
This change is [Reviewable](https://reviewable.io/reviews/Reviewable/Reviewable/1006)

### CODE REVIEW

**Review by pkaminski — COMMENTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Reviewable/Reviewable/1006)* status: all files reviewed, 1 unresolved discussion (waiting on @snoack)

___
*[`enterprise/changelog.md` line 12 at r1](https://reviewable.io/reviews/Reviewable/Reviewable/1006#-NOL_-rx7dDbUaHyNCvU:-NOL_-rx7dDbUaHyNCvV:bh8z9w8) ([raw file](https://github.com/Reviewable/Reviewable/blob/b523c006c2316d1c937266c59eca87287a818773/enterprise/changelog.md#L12)):*
> ```Markdown
> - Fix: correctly style notification emails.
> - Fix: ensure that some rare permission / token errors are attributed to the right user and will correctly cause a repository to be disconnected.
> - Upd: add support for disabled repository connections via the `REVIEWABLE_DISABLED_CONNECTIONS` environment variable.
> ```

Minor:  we order changelog entries for a version as new - upd - fix.  (The order within each section doesn't matter.)

**Review by snoack — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Reviewable/Reviewable/1006)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @pkaminski)

___
*[`enterprise/changelog.md` line 12 at r1](https://reviewable.io/reviews/Reviewable/Reviewable/1006#-NOL_-rx7dDbUaHyNCvU:-NOLcRfL05mJmGpyBc3V:b-1028qz) ([raw file](https://github.com/Reviewable/Reviewable/blob/b523c006c2316d1c937266c59eca87287a818773/enterprise/changelog.md#L12)):*
<details><summary><i>Previously, pkaminski (Piotr Kaminski) wrote…</i></summary><blockquote>

Minor:  we order changelog entries for a version as new - upd - fix.  (The order within each section doesn't matter.)
</blockquote></details>

I moved it to the top. Also I didn't realize `New` was a category, I suppose that would be more appropriate than `Upd` here, right?

BTW, I didn't get a "Done" button here (after pushing the changes) either:

**Review by pkaminski — COMMENTED** [review]
:lgtm:, but please wait to merge until all the relevant changes have been merged themselves.

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Reviewable/Reviewable/1006#-:-NOLdhRO4gFfFPDqD83k:bbng1e4)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @snoack)

___
*[`enterprise/changelog.md` line 12 at r1](https://reviewable.io/reviews/Reviewable/Reviewable/1006#-NOL_-rx7dDbUaHyNCvU:-NOLd1Q72c8lirTDzt0r:bj1lnad) ([raw file](https://github.com/Reviewable/Reviewable/blob/b523c006c2316d1c937266c59eca87287a818773/enterprise/changelog.md#L12)):*
<details><summary><i>Previously, snoack (Sebastian Noack) wrote…</i></summary><blockquote>

I moved it to the top. Also I didn't realize `New` was a category, I suppose that would be more appropriate than `Upd` here, right?

BTW, I didn't get a "Done" button here (after pushing the changes) either:


</blockquote></details>

Agreed, `New` is better.  We don't see a lot of those!

I should've been more precise:  "Done" shows up only if the discussion isn't resolved and you, as the author, can't resolve it (i.e., a reviewer is Blocking).  Otherwise, you'll just get the option to Resolve the discussion immediately.  You can find the full (and surprisingly non-trivial!) logic for this button's label in `reviews.$reviewKey.tracker.$discussionKey` at `get primaryAction()`.

**Comment by snoack** [comment]
@pkaminski It seems all related changes have been merged. Can I go ahead and merge this PR now?

**Review by pkaminski — COMMENTED** [review]
Yup, please go ahead.  I'm deploying your code now.  :)

> *[Reviewable](https://reviewable.io/reviews/Reviewable/Reviewable/1006#-:-NOLzcx54SgH5_y506NQ:b1rpygl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @snoack)

**Pull request merged**
