### PR TITLE
Docs for `REVIEWABLE_REFS_DELETION_DELAY`.

### PR DESCRIPTION
**Pull request by pkaminski**
Docs for https://github.com/Reviewable/reviewable-server/pull/551.

- - -
This change is [Reviewable](https://reviewable.io/reviews/Reviewable/Reviewable/1156)

### CODE REVIEW

**Review by snoack — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Reviewable/Reviewable/1156)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @pkaminski)

___
*[`enterprise/config.md` line 67 at r1](https://reviewable.io/reviews/Reviewable/Reviewable/1156#-NxYfBS_5B5EcSjaQB44:-NxYfBS_5B5EcSjaQB45:b-t273w9) ([raw file](https://github.com/Reviewable/Reviewable/blob/2f73a1789f0fe57a5c9fcb7ad24d56658adbb13f/enterprise/config.md#L67)):*
> ```Markdown
> * `REVIEWABLE_GITHUB_CLIENT_SECRET`: The hex client secret assigned to the GitHub application you created above.
> * `REVIEWABLE_HOST_INACCESSIBLE`: (optional) Set to a non-empty value if your `REVIEWABLE_HOST_URL` is not reachable from `REVIEWABLE_GITHUB_URL`.  This will redirect incoming requests from GitHub either directly to your Firebase (for webhooks) or to `reviewable.io` (for images).
> * `REVIEWABLE_REFS_DELETION_DELAY`: (optional but recommended) Set to a [human-readable](https://github.com/vercel/ms) duration (e.g., `3y`) to have Reviewable clean up the refs it creates in your repository to prevent revision commits from being garbage collected, even if they were force-pushed aside.  The refs for any pull requests that have been closed or merged for at least this long and that don't have a `Retain all Reviewable commits` (exact spelling!) will be eventually cleared.  If there are no other references to those commits then they may be garbage collected by `git` and you won't be able to diff the corresponding revisions in the review any more, but any discussions will remain (though might not be placed on the right line).
> ```

Nit: Redundant coma after "e.g."

**Review by pkaminski — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Reviewable/Reviewable/1156)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @snoack)

___
*[`enterprise/config.md` line 67 at r1](https://reviewable.io/reviews/Reviewable/Reviewable/1156#-NxYfBS_5B5EcSjaQB44:-NxYgx7B8MOTITd9nKFu:b-o2xp2v) ([raw file](https://github.com/Reviewable/Reviewable/blob/2f73a1789f0fe57a5c9fcb7ad24d56658adbb13f/enterprise/config.md#L67)):*
<details><summary><i>Previously, snoack (Sebastian Noack) wrote…</i></summary><blockquote>

Nit: Redundant coma after "e.g."
</blockquote></details>

I'm in the "e.g. always needs a comma" camp.  :)  Apparently it's a difference between American and British styles.  https://english.stackexchange.com/questions/16172/should-i-always-use-a-comma-after-e-g-or-i-e

**Review by snoack — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Reviewable/Reviewable/1156)* status: 0 of 1 files reviewed, all discussions resolved

___
*[`enterprise/config.md` line 67 at r1](https://reviewable.io/reviews/Reviewable/Reviewable/1156#-NxYfBS_5B5EcSjaQB44:-NxYiRfeAnNKCXxAV4Km:b-m4w8md) ([raw file](https://github.com/Reviewable/Reviewable/blob/2f73a1789f0fe57a5c9fcb7ad24d56658adbb13f/enterprise/config.md#L67)):*
<details><summary><i>Previously, pkaminski (Piotr Kaminski) wrote…</i></summary><blockquote>

I'm in the "e.g. always needs a comma" camp.  :)  Apparently it's a difference between American and British styles.  https://english.stackexchange.com/questions/16172/should-i-always-use-a-comma-after-e-g-or-i-e
</blockquote></details>

Interesting.

**Review by snoack — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/Reviewable/Reviewable/1156#-:-NxYiUs766AVMIPAGEQ-:bnfp4nl)* status: 0 of 1 files reviewed, all discussions resolved

**Pull request merged**
