### PR TITLE
Added docs for color scheme

### PR DESCRIPTION
**Pull request by BlackVegetable**
Updates documentation to include a blurb about color scheme options (light, dark, system.) Needs to have an updated display image showing the panel including these elements as well. I suppose I could use a screenshot of this very PR to do so.

- - -
This change is [Reviewable](https://reviewable.io/reviews/Reviewable/Reviewable/1174)

### CODE REVIEW

**Review by BlackVegetable — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Reviewable/Reviewable/1174)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @pkaminski)

*[a discussion](https://reviewable.io/reviews/Reviewable/Reviewable/1174#-O4zqyap505tBF9Ivyhy:-O4zqyap505tBF9Ivyhz:b-i3i5j0) (no related file):*
FYI: this should be ready for review. I did have a mess-up where I uploaded an image with the same name and tried to delete and then replace it with an updated version that included a red box. Github displayed some odd caching behavior in the display, so make sure the image that you see is both satisfactory and includes the red box.

___

**Review by pkaminski — COMMENTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Reviewable/Reviewable/1174)* status: all files reviewed, 1 unresolved discussion (waiting on @BlackVegetable)

*[a discussion](https://reviewable.io/reviews/Reviewable/Reviewable/1174#-O4zqyap505tBF9Ivyhy:-O5-NijkAkhvs53Ph76N:bj38p43) (no related file):*
<details><summary><i>Previously, BlackVegetable (Devin Ekins) wrote…</i></summary><blockquote>

FYI: this should be ready for review. I did have a mess-up where I uploaded an image with the same name and tried to delete and then replace it with an updated version that included a red box. Github displayed some odd caching behavior in the display, so make sure the image that you see is both satisfactory and includes the red box.
</blockquote></details>

Image LGTM!

___
___
*[`docs/images/accountsettings_3.png` line 0 at r1](https://reviewable.io/reviews/Reviewable/Reviewable/1174#-O5-N_A7AMIQYJDLqx5P:-O5-N_A7AMIQYJDLqx5Q:barcucc) ([raw file](https://github.com/Reviewable/Reviewable/blob/d52c676a47af22d2730cd7e1bfe5bc25b8219154/docs/images/accountsettings_3.png#L0)):*
Since this replaces `accountsettings_1.png` please give it the same name, so we don't have obsolete screenshots hanging around.

**Review by BlackVegetable — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Reviewable/Reviewable/1174)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @pkaminski)

___
*[`docs/images/accountsettings_3.png` line  at r1](https://reviewable.io/reviews/Reviewable/Reviewable/1174#-O5-N_A7AMIQYJDLqx5P:-O5-SnHc4Xg94WX9kYuk:b-896fix) ([raw file](https://github.com/Reviewable/Reviewable/blob/d52c676a47af22d2730cd7e1bfe5bc25b8219154/docs/images/accountsettings_3.png#L)):*
<details><summary><i>Previously, pkaminski (Piotr Kaminski) wrote…</i></summary><blockquote>

Since this replaces `accountsettings_1.png` please give it the same name, so we don't have obsolete screenshots hanging around.
</blockquote></details>

Done.

**Review by pkaminski — COMMENTED** [review]
:lgtm:

> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Reviewable/Reviewable/1174#-:-O5-SucH4S6Bw_xXiH8P:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @BlackVegetable)

**Pull request merged**
