### PR TITLE
Document all the disposition-setting words

### PR DESCRIPTION
**Pull request by fahhem**
This change is [Reviewable](https://reviewable.io/reviews/Reviewable/Reviewable/1023)

### CODE REVIEW

**Review by pkaminski — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Reviewable/Reviewable/1023)* status: all files reviewed, 2 unresolved discussions (waiting on @fahhem)

___
*[`docs/discussions.md` line 127 at r1](https://reviewable.io/reviews/Reviewable/Reviewable/1023#-NRJqUR93tBtFmcW0fg6:-NRJqURA9TiQcOI2hTVH:b-98kc9l) ([raw file](https://github.com/Reviewable/Reviewable/blob/c3014acf46cf4876737a44d92a4943a134ec3559/docs/discussions.md#L127)):*
> ```Markdown
> reviewable dispositions
> 
> You can also change your disposition as you're writing your comment without touching the mouse. When you create a new draft notice — before you begin typing — the small list of disposition mappings in the lower-right corner of the draft box. These are some examples of what you'll find there:
> ```

Since the list is now exhaustive we should change the phrasing of "these are some examples..."
___
*[`docs/discussions.md` line 133 at r1](https://reviewable.io/reviews/Reviewable/Reviewable/1023#-NRJqgvL9U3fxYd6kK_T:-NRJqgvL9U3fxYd6kK_U:b-pyohms) ([raw file](https://github.com/Reviewable/Reviewable/blob/c3014acf46cf4876737a44d92a4943a134ec3559/docs/discussions.md#L133)):*
> ```Markdown
> * Working or Will do → **<i class="fa fa-play-circle"></i> Working**
> * ??? → **<i class="fa fa-play-circle"></i> Pondering**
> * Bug, Major, or Hold on → **<i class="fa fa-play-circle"></i> Blocking**
> ```

I'd try to match the order of the in-draft tips (roughly of increasing "severity") and move Blocking to just after Discussing.

**Review by pkaminski — COMMENTED** [review]
:lgtm:, but should probably wait to merge until the "thanks" PRs land.  (Should we merge those and deal with potential code sharing separately later?)

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Reviewable/Reviewable/1023#-:-NRJscNyEa1p3aHE3z0Z:b-39z1re)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @fahhem)

**Review by fahhem — COMMENTED** [review]
Yeah, code sharing is not a same-day thing

> *[Reviewable](https://reviewable.io/reviews/Reviewable/Reviewable/1023#-:-NRJt2td8e9pV96xqw6w:b-ksig2u)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @fahhem)

**Review by pkaminski — COMMENTED** [review]
Done.  (And incidentally noticed that we highlight keywords in the main discussion even though we don't support dispositions there.  Oops -- will fix.)

> *[Reviewable](https://reviewable.io/reviews/Reviewable/Reviewable/1023#-:-NRJtMp9CKrptzhFnUmE:b-2gocgn)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @fahhem)

**Pull request merged**
