### PR TITLE
Document requirement of repositories being connected for setting files

### PR DESCRIPTION
**Pull request by snoack**
This change is [Reviewable](https://reviewable.io/reviews/Reviewable/Reviewable/1177)

### CODE REVIEW

**Review by pkaminski — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Reviewable/Reviewable/1177)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @snoack)

**Review by snoack — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Reviewable/Reviewable/1177)* status: all files reviewed, 1 unresolved discussion (waiting on @pkaminski)

___
*[`docs/repositories.md` line 148 at r1](https://reviewable.io/reviews/Reviewable/Reviewable/1177#-O5GAlTg5r29TkfSS5dE:-O5GAlTg5r29TkfSS5dF:b-5jweq6) ([raw file](https://github.com/Reviewable/Reviewable/blob/b395ab08a18e7169a598c0a6431eeebc1792f8de/docs/repositories.md#L148)):*
> ```Markdown
> * "The current prototype repository is ____.".
> 
> ### Applying a `settings.yaml` file to multiple repositories
> ```

Shouldn't this be a sub section of `Store repository settings using the .reviewable directory`?

**Review by pkaminski — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Reviewable/Reviewable/1177)* status: all files reviewed, 1 unresolved discussion (waiting on @snoack)

___
*[`docs/repositories.md` line 148 at r1](https://reviewable.io/reviews/Reviewable/Reviewable/1177#-O5GAlTg5r29TkfSS5dE:-O5GJGcf3DmNsDJG9W4r:b29vn2b) ([raw file](https://github.com/Reviewable/Reviewable/blob/b395ab08a18e7169a598c0a6431eeebc1792f8de/docs/repositories.md#L148)):*
<details><summary><i>Previously, snoack (Sebastian Noack) wrote…</i></summary><blockquote>

Shouldn't this be a sub section of `Store repository settings using the .reviewable directory`?
</blockquote></details>

I think right now we have separate sections for "how to change settings" and "how to make the settings you've set apply to other repos".  But maybe the sections should be reordered so that GUI stuff and file stuff is grouped together:  GUI settings, prototype, .reviewable settings, master settings?

**Review by snoack — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Reviewable/Reviewable/1177)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @snoack)

___
*[`docs/repositories.md` line 148 at r1](https://reviewable.io/reviews/Reviewable/Reviewable/1177#-O5GAlTg5r29TkfSS5dE:-O5GL_6xAmKdbanAuwld:b-xkatnv) ([raw file](https://github.com/Reviewable/Reviewable/blob/b395ab08a18e7169a598c0a6431eeebc1792f8de/docs/repositories.md#L148)):*
<details><summary><i>Previously, pkaminski (Piotr Kaminski) wrote…</i></summary><blockquote>

I think right now we have separate sections for "how to change settings" and "how to make the settings you've set apply to other repos".  But maybe the sections should be reordered so that GUI stuff and file stuff is grouped together:  GUI settings, prototype, .reviewable settings, master settings?
</blockquote></details>

Agreed, that would already be an improvement. Done.

**Review by pkaminski — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Reviewable/Reviewable/1177#-:-O5GhZnXEkhmT1z8p6wr:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @snoack)

**Pull request merged**
