### PR TITLE
Update docs for new subscriptions design and add docs on licenses.

### PR DESCRIPTION
**Pull request by pkaminski**
Hey @snoack, could you please review my edits, and update the rest of the Subscriptions section to reflect the recent changes?  Thanks.

- - -
This change is [Reviewable](https://reviewable.io/reviews/Reviewable/Reviewable/1148)

### CODE REVIEW

**Review by snoack — COMMENTED** [review]
What else should be covered? Billing delegation, I suppose?

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Reviewable/Reviewable/1148#-:-Nt1fV5h4rK6b-V3ZcGH:bk1fkz3)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @pkaminski)

**Review by pkaminski — COMMENTED** [review]
A lot of the old text is no longer accurate (e.g., explanation of plans, one card per user, likely more).  And yeah, any new features need to be explained too.

> *[Reviewable](https://reviewable.io/reviews/Reviewable/Reviewable/1148#-:-Nt23e3W3_gnVncW-2vX:b-ty3dty)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @pkaminski)

**Review by snoack — COMMENTED** [review]
Do you want me to add commits to this branch, or submit a separate review?

> *[Reviewable](https://reviewable.io/reviews/Reviewable/Reviewable/1148#-:-Nt2CpMRBaJkoMzvJvP6:biiztqe)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @pkaminski)

**Review by pkaminski — COMMENTED** [review]
On this branch is fine, doesn't really matter.

> *[Reviewable](https://reviewable.io/reviews/Reviewable/Reviewable/1148#-:-Nt2UMP69oICUNTetZ2D:b-2t9m0u)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @pkaminski)

**Review by snoack — COMMENTED** [review]
There you go, PTAL.

> *[Reviewable](https://reviewable.io/reviews/Reviewable/Reviewable/1148#-:-Nt3_CTA5Y5JBTYnzTxF:b-g5x8lb)* status: 1 of 2 files reviewed, all discussions resolved (waiting on @pkaminski)

**Review by pkaminski — COMMENTED** [review]
:lgtm:, thanks.  I'll merge.

> Reviewed 1 of 2 files at r1, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Reviewable/Reviewable/1148#-:-Nt3ayH0C49dK-NcXnYX:b-r8xjew)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @pkaminski)

**Pull request merged**
