### PR TITLE
Update Rename Documentation

### PR DESCRIPTION
**Pull request by BlackVegetable**
I think most of the rename file reference work should be in a feature post which should probably be in a different PR. However, I would like to include one image that demonstrates a special message that isn't currently displayed in the docs despite being referenced.

- - -
This change is [Reviewable](https://reviewable.io/reviews/Reviewable/Reviewable/1176)

### CODE REVIEW

**Review by pkaminski — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Reviewable/Reviewable/1176)* status: all files reviewed, 1 unresolved discussion (waiting on @BlackVegetable)

___
*[`docs/files.md` line 120 at r2](https://reviewable.io/reviews/Reviewable/Reviewable/1176#-O5Fy9I04cDc_6wIB24c:-O5Fy9I04cDc_6wIB24d:belyyio) ([raw file](https://github.com/Reviewable/Reviewable/blob/874985987e5d1853b005df055c1d8b70347e2304/docs/files.md#L120)):*
> ```Markdown
> 
> {:.tip}
> Any special messages will appear immediately underneath the header.  These include rename sequence details, explanations for why a diff isn't showing, etc.
> ```

Maybe we should fix this while you're here:  we no longer show the rename sequence like we used to, but just any effective rename between current diff bounds (plus a warning about reintroduction, if appropriate).

**Review by BlackVegetable — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Reviewable/Reviewable/1176)* status: 1 of 2 files reviewed, all discussions resolved (waiting on @BlackVegetable)

___
*[`docs/files.md` line 120 at r2](https://reviewable.io/reviews/Reviewable/Reviewable/1176#-O5Fy9I04cDc_6wIB24c:-O5JmJ7H-dGuWla5Y-lM:b-bw8e14) ([raw file](https://github.com/Reviewable/Reviewable/blob/874985987e5d1853b005df055c1d8b70347e2304/docs/files.md#L120)):*
<details><summary><i>Previously, pkaminski (Piotr Kaminski) wrote…</i></summary><blockquote>

Maybe we should fix this while you're here:  we no longer show the rename sequence like we used to, but just any effective rename between current diff bounds (plus a warning about reintroduction, if appropriate).
</blockquote></details>

Updated.

**Review by BlackVegetable — COMMENTED** [review]
Odd, why is Reviewable saying it's still my turn?

> *[Reviewable](https://reviewable.io/reviews/Reviewable/Reviewable/1176#-:-O5Jmlry7qz3oqsJhuUJ:b-mhvhkc)* status: 1 of 2 files reviewed, all discussions resolved (waiting on @BlackVegetable)

**Review by pkaminski — COMMENTED** [review]
Our custom completion condition got backed into a corner.  It's written to cue solely off of discussions (ignoring file state), but you (correctly) resolved the only blocking discussion so it didn't find any blocking participants and fell back on the PR's author.  I should probably rewrite the condition someday but it works reasonably well in most cases...  Getting "[Publish on push](https://github.com/Reviewable/Reviewable/issues/1104)" done would also alleviate the reason for having a custom condition in the first place.

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Reviewable/Reviewable/1176#-:-O5JvTLmBdZhllbvvu6v:bw1jd9i)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @BlackVegetable)

**Pull request merged**
