### PR TITLE
Tweak text re: vendored files -  process is automatic and flags files…

### PR DESCRIPTION
**Pull request by unforswearing**
… as vendored.

- - -
This change is [Reviewable](https://reviewable.io/reviews/Reviewable/Reviewable/1165)

### CODE REVIEW

**Review by pkaminski — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Reviewable/Reviewable/1165)* status: all files reviewed, 1 unresolved discussion (waiting on @unforswearing)

___
*[`docs/tips.md` line 91 at r1](https://reviewable.io/reviews/Reviewable/Reviewable/1165#-O-P6Cpt1QVfzKNWjlbo:-O-P6Cpt1QVfzKNWjlbp:bj3wrkc) ([raw file](https://github.com/Reviewable/Reviewable/blob/ace7d46c6ae613a26d89751dca6c6db54dc6bab3/docs/tips.md#L91)):*
> ```Markdown
> 
> 1. [Suppress diffs](files.md#diff-suppression-and-file-type) for vendored files via `.gitattributes`.
> 2. Use a custom review completion condition to [group vendored files](repositories.md#files) in the file matrix, which will allow you to mark them all as reviewed and flag them as "vendored" with one click.
> ```

See suggested edit below.  It would also be nice to make a sample condition and link it here instead of (or in addition to) the generic docs.



_Suggestion:_
```Markdown
2. Use a custom review completion condition to [identify files as vendored](repositories.md#files) in the file matrix, which will allow you to mark them all as reviewed with one click.
```

**Comment by unforswearing** [comment]
Thanks for the suggestion, sorry for the delay. I have applied the change. 

> It would also be nice to make a sample condition and link it here instead of (or in addition to) the generic docs.

I can create a sample and update the docs later this evening. Should I add it to [`examples/conditions`](https://github.com/Reviewable/Reviewable/tree/master/examples/conditions)?

**Review by pkaminski — COMMENTED** [review]
> I can create a sample and update the docs later this evening. Should I add it to [`examples/conditions`](https://github.com/Reviewable/Reviewable/tree/master/examples/conditions)?

Yes please.

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Reviewable/Reviewable/1165#-:-O-c-cJQCkwe-C1pz58x:b-luvk37)* status: all files reviewed, 1 unresolved discussion (waiting on @unforswearing)

**Comment by unforswearing** [comment]
Added `identify_vendored_files.js` using the `third_party` directory as the example, and updated the docs.

**Review by pkaminski — COMMENTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Reviewable/Reviewable/1165)* status: all files reviewed, 2 unresolved discussions (waiting on @unforswearing)

___
*[`examples/conditions/identify_vendored_files.js` line 13 at r3](https://reviewable.io/reviews/Reviewable/Reviewable/1165#-O004GOw2rgPzfaX35rA:-O004GOw2rgPzfaX35rB:ble1xwl) ([raw file](https://github.com/Reviewable/Reviewable/blob/ef12115a06ceadaa82784b0c79d9f9479a0b9e28/examples/conditions/identify_vendored_files.js#L13)):*
> ```JavaScript
>   if (/^third_party$/i.test(file.path)) {
>     _.forEach(file.revisions, (rev) => {
>       rev.reviewed = true;
> ```

You mark files as vendored by setting `file.vendored = true`.  While you might want to set their revisions as `reviewed` at the same time, that's a separate and orthogonal flag.
___
*[`examples/conditions/identify_vendored_files.js` line 21 at r3](https://reviewable.io/reviews/Reviewable/Reviewable/1165#-O004Rh_5hdyDKK7xsNz:-O004Rh_5hdyDKK7xsO-:b2nv78f) ([raw file](https://github.com/Reviewable/Reviewable/blob/ef12115a06ceadaa82784b0c79d9f9479a0b9e28/examples/conditions/identify_vendored_files.js#L21)):*
> ```JavaScript
> return {
>   files: review.files,
> };
> ```

Please remove trailing spaces throughout, and make sure there's a newline on the final line.  (You can probably set up your editor to do this automatically on save.)

**Review by unforswearing — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Reviewable/Reviewable/1165)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @pkaminski)

___
*[`examples/conditions/identify_vendored_files.js` line 13 at r3](https://reviewable.io/reviews/Reviewable/Reviewable/1165#-O004GOw2rgPzfaX35rA:-O17Wx83BAHfzw7FTgio:b-896fix) ([raw file](https://github.com/Reviewable/Reviewable/blob/ef12115a06ceadaa82784b0c79d9f9479a0b9e28/examples/conditions/identify_vendored_files.js#L13)):*
<details><summary><i>Previously, pkaminski (Piotr Kaminski) wrote…</i></summary><blockquote>

You mark files as vendored by setting `file.vendored = true`.  While you might want to set their revisions as `reviewed` at the same time, that's a separate and orthogonal flag.
</blockquote></details>

Done.

**Review by pkaminski — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Reviewable/Reviewable/1165#-:-O188UQg4c_J8ABApgJ0:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @unforswearing)

**Pull request merged**
