### PR TITLE
Update docs for commit reviewing

### PR DESCRIPTION
**Pull request by cgiroux86**
Update docs for commit reviewing

---
This change is [Reviewable](https://reviewable.io/reviews/reviewable/reviewable/852)

### CODE REVIEW

**Review by pkaminski — COMMENTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/reviewable/reviewable/852)* status: all files reviewed, 4 unresolved discussions (waiting on @cgiroux86)

___
*[docs/repositories.md, line 283 at r1](https://reviewable.io/reviews/reviewable/reviewable/852#-MfdhiwHBrNSJSfBQdXE:-MfdhiwHBrNSJSfBQdXF:b-1r6w6t) ([raw file](https://github.com/reviewable/reviewable/blob/e01d3bb97df26ceae32a5f3cdad8f71d1027b340/docs/repositories.md#L283)):*
> ```Markdown
>     }
>   ],
>   systemFiles: [ // System files used by Reviewable, including commit file
> ```

used by -> generated by ?
___
*[docs/repositories.md, line 289 at r1](https://reviewable.io/reviews/reviewable/reviewable/852#-Mfdhpji0fzeGGjykVDp:-Mfdhpji0fzeGGjykVDq:boa3nmo) ([raw file](https://github.com/reviewable/reviewable/blob/e01d3bb97df26ceae32a5f3cdad8f71d1027b340/docs/repositories.md#L289)):*
> ```Markdown
>         {
>           key: 'r1',
>           action: 'added',  // one of 'added', 'modified'
> ```

Future system files could also be `removed`, so should include that in comment even if it doesn't occur for commits.
___
*[docs/reviews.md, line 253 at r1](https://reviewable.io/reviews/reviewable/reviewable/852#-MfdiKWp9q_lqetoLpUb:-MfdiKWp9q_lqetoLpUc:bm7pxry) ([raw file](https://github.com/reviewable/reviewable/blob/e01d3bb97df26ceae32a5f3cdad8f71d1027b340/docs/reviews.md#L253)):*
> ```Markdown
> ## Reviewing commit messages
> 
> Reviewable composes a system file used for reviewing commit messages.  The **commit file** is denoted with a special commit icon prepended to its name and will always be listed first in the files list (matrix and review).  This file will contain a list of all *non obsolete* commit messages that precede it, regardless of whether you're reviewing with the **combined commits** or **commit-by-commit** review style.  It behaves just like a normal file in that it will be diffed against the selected revision and supports discussions, however it *will not* impact your repo or PR in anyway -- its solely used by Reviewable for reviewing commit messages.
> ```

its -> it's

Also, while it won't impact the repo or PR, it will impact the review in that it needs to be marked as reviewed the same as any other file (which necessity varies depending on the team's workflow).  I think this should be addressed explicitly, either here or below.
___
*[docs/reviews.md, line 259 at r1](https://reviewable.io/reviews/reviewable/reviewable/852#-MfdjrYyBsUuR80qqRAy:-MfdjrYz3ToXdmY-kLIA:bjisgoy) ([raw file](https://github.com/reviewable/reviewable/blob/e01d3bb97df26ceae32a5f3cdad8f71d1027b340/docs/reviews.md#L259)):*
> ```Markdown
> reviewable commit review
> 
> Note the **commit file** is included in **review.systemFiles** should you want to adjust your [custom completion condition](repositories.md#custom-review-completion-condition) to include it.  Further, the [condition ouput](#repositories.md#condition-output) will only reference the **commit file** if it differs from the overall state of the review (e.g. all files except the commit file have been reviewed).
> ```

I'd change this into a `.tip`, maybe along these lines:

While the commit file is virtual, it needs to be marked as reviewed as much (or as little) as normal files.  It's included in review file counters, but not counted in review status messages unless it's the only unreviewed file.  It's also handled separately from normal files when evaluating a custom review completion condition; see [] for details.

**Review by cgiroux86 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/reviewable/reviewable/852)* status: 2 of 4 files reviewed, 3 unresolved discussions (waiting on @pkaminski)

___
*[docs/repositories.md, line 283 at r1](https://reviewable.io/reviews/reviewable/reviewable/852#-MfdhiwHBrNSJSfBQdXE:-MfhAn3n1UcA3-9MFIz3:b-896fix) ([raw file](https://github.com/reviewable/reviewable/blob/e01d3bb97df26ceae32a5f3cdad8f71d1027b340/docs/repositories.md#L283)):*
<details><summary><i>Previously, pkaminski (Piotr Kaminski) wrote…</i></summary><blockquote>

used by -> generated by ?
</blockquote></details>

Done.
___
*[docs/repositories.md, line 289 at r1](https://reviewable.io/reviews/reviewable/reviewable/852#-Mfdhpji0fzeGGjykVDp:-MfhAo3Y4U2ion2h2LkB:b-896fix) ([raw file](https://github.com/reviewable/reviewable/blob/e01d3bb97df26ceae32a5f3cdad8f71d1027b340/docs/repositories.md#L289)):*
<details><summary><i>Previously, pkaminski (Piotr Kaminski) wrote…</i></summary><blockquote>

Future system files could also be `removed`, so should include that in comment even if it doesn't occur for commits.
</blockquote></details>

Done.
___
*[docs/reviews.md, line 253 at r1](https://reviewable.io/reviews/reviewable/reviewable/852#-MfdiKWp9q_lqetoLpUb:-MfhCaPE0kPf-xeR4vb0:b-896fix) ([raw file](https://github.com/reviewable/reviewable/blob/e01d3bb97df26ceae32a5f3cdad8f71d1027b340/docs/reviews.md#L253)):*
<details><summary><i>Previously, pkaminski (Piotr Kaminski) wrote…</i></summary><blockquote>

its -> it's

Also, while it won't impact the repo or PR, it will impact the review in that it needs to be marked as reviewed the same as any other file (which necessity varies depending on the team's workflow).  I think this should be addressed explicitly, either here or below.
</blockquote></details>

Done.
___
*[docs/reviews.md, line 259 at r1](https://reviewable.io/reviews/reviewable/reviewable/852#-MfdjrYyBsUuR80qqRAy:-MfhE6BLBynKc0Jy63RO:b-896fix) ([raw file](https://github.com/reviewable/reviewable/blob/e01d3bb97df26ceae32a5f3cdad8f71d1027b340/docs/reviews.md#L259)):*
<details><summary><i>Previously, pkaminski (Piotr Kaminski) wrote…</i></summary><blockquote>

I'd change this into a `.tip`, maybe along these lines:

While the commit file is virtual, it needs to be marked as reviewed as much (or as little) as normal files.  It's included in review file counters, but not counted in review status messages unless it's the only unreviewed file.  It's also handled separately from normal files when evaluating a custom review completion condition; see [] for details.
</blockquote></details>

Done.

**Review by pkaminski — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/reviewable/reviewable/852)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @cgiroux86)

**Review by pkaminski — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/reviewable/reviewable/852)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @cgiroux86)

**Pull request merged**
