### PR TITLE
Initial Reviewable >> Postgres >> Grafana pipeline

### PR DESCRIPTION
**Pull request by fahhem**
This change is [Reviewable](https://reviewable.io/reviews/Reviewable/Reviewable/1079)

### CODE REVIEW

**Review by pkaminski — COMMENTED** [review]
I reviewed mostly just for internal consistency -- I don't claim to understand Postgres, Grafana, or Docker composition, and didn't attempt to run any of this code.

Is the intention to bundle this into Reviewable's server?  If so, it may be worthwhile to copy its `eslint` configuration and delint.  (I spotted a number of potential style issues but it's not something worth wasting time over for an example.)

> Reviewed 11 of 12 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Reviewable/Reviewable/1079#-:-NZUdCzO-NpwjV-pOVZf:b72ofy)* status: all files reviewed, 4 unresolved discussions (waiting on @fahhem)

___
*[`examples/analytics/typescript-postgres-grafana/README.md` line 12 at r2](https://reviewable.io/reviews/Reviewable/Reviewable/1079#-NZUaJu607ZW5FKF48wv:-NZUaJu607ZW5FKF48ww:b-bohwsm) ([raw file](https://github.com/Reviewable/Reviewable/blob/111d4168cf161d428e06e4dee0005709625ae6da/examples/analytics/typescript-postgres-grafana/README.md#L12)):*
> ```Markdown
> 
> **NOTE**: There is an insecure password in `docker-compose.yml` that should be
> changed if you're running this in production, and it's matched in ormconfig.json.
> ```

`ormconfig.json` is empty, and the password is in `ormconfig.ts`, so something doesn't line up.
___
*[`examples/analytics/typescript-postgres-grafana/src/ormconfig.ts` line 4 at r2](https://reviewable.io/reviews/Reviewable/Reviewable/1079#-NZUad7M80prD_vFGq_P:-NZUad7M80prD_vFGq_Q:b-nzn6o0) ([raw file](https://github.com/Reviewable/Reviewable/blob/111d4168cf161d428e06e4dee0005709625ae6da/examples/analytics/typescript-postgres-grafana/src/ormconfig.ts#L4)):*
> ```XML
> const ormconfig : DataSourceOptions = {
>   type: "postgres",
>   host: "172.19.0.2",
> ```

Is this hardcoded IP intended?
___
*[`examples/analytics/typescript-postgres-grafana/src/server.ts` line 12 at r2](https://reviewable.io/reviews/Reviewable/Reviewable/1079#-NZUbd8F4rVJ0022Zo0y:-NZUbd8F4rVJ0022Zo0z:b-mvfm9b) ([raw file](https://github.com/Reviewable/Reviewable/blob/111d4168cf161d428e06e4dee0005709625ae6da/examples/analytics/typescript-postgres-grafana/src/server.ts#L12)):*
> ```XML
>   entities: [Event, User],
> };
> if (true) {  // dev-only
> ```

Do you want to check `process.env.NODE_ENV !== 'production'` instead?
___
*[`examples/analytics/typescript-postgres-grafana/src/server.ts` line 18 at r2](https://reviewable.io/reviews/Reviewable/Reviewable/1079#-NZUbxP35fOJ1g2ygtVP:-NZUbxP35fOJ1g2ygtVQ:b-yl7fr5) ([raw file](https://github.com/Reviewable/Reviewable/blob/111d4168cf161d428e06e4dee0005709625ae6da/examples/analytics/typescript-postgres-grafana/src/server.ts#L18)):*
> ```XML
> const dataSourceReady = dataSource.initialize();
> dataSourceReady.catch((err) => {
>   console.error("Error during data source init:", err)
> ```

Nit:  I'd pick either `'` (Reviewable preferred) or `"` for string delimiters and stick with it throughout, just to be easier on the eyes if nothing else.

**Review by fahhem — COMMENTED** [review]
This can run anywhere. I think for {insert customer}, they would likely prefer a separate container anyway. I can copy over the eslint to improve the style though. I'll update the few diffs noted in a bit

> *[Reviewable](https://reviewable.io/reviews/Reviewable/Reviewable/1079#-:-NZUmIDt4a1K4RuqYCLE:b-6s6vey)* status: all files reviewed, 5 unresolved discussions (waiting on @pkaminski)

___
*[`examples/analytics/typescript-postgres-grafana/README.md` line 12 at r2](https://reviewable.io/reviews/Reviewable/Reviewable/1079#-NZUaJu607ZW5FKF48wv:-NZUmk3PAiHsLkYLXgCD:b-o6kkf9) ([raw file](https://github.com/Reviewable/Reviewable/blob/111d4168cf161d428e06e4dee0005709625ae6da/examples/analytics/typescript-postgres-grafana/README.md#L12)):*
<details><summary><i>Previously, pkaminski (Piotr Kaminski) wrote…</i></summary><blockquote>

`ormconfig.json` is empty, and the password is in `ormconfig.ts`, so something doesn't line up.
</blockquote></details>

If only I could just apply a suggestion here...



_Suggestion:_
```Markdown
changed if you're running this in production, and it's matched in ormconfig.ts.
```
___
*[`examples/analytics/typescript-postgres-grafana/src/ormconfig.ts` line 4 at r2](https://reviewable.io/reviews/Reviewable/Reviewable/1079#-NZUad7M80prD_vFGq_P:-NZUn96R05VcEZkow7Lf:bg1y1ui) ([raw file](https://github.com/Reviewable/Reviewable/blob/111d4168cf161d428e06e4dee0005709625ae6da/examples/analytics/typescript-postgres-grafana/src/ormconfig.ts#L4)):*
<details><summary><i>Previously, pkaminski (Piotr Kaminski) wrote…</i></summary><blockquote>

Is this hardcoded IP intended?
</blockquote></details>

nope! we can use the docker-compose service name though



_Suggestion:_
```XML
  host: "reviewable-analytics-postgres",
```
___
*[`examples/analytics/typescript-postgres-grafana/src/server.ts` line 12 at r2](https://reviewable.io/reviews/Reviewable/Reviewable/1079#-NZUbd8F4rVJ0022Zo0y:-NZUnHil8oM9pVqJ10ng:bl4lwrp) ([raw file](https://github.com/Reviewable/Reviewable/blob/111d4168cf161d428e06e4dee0005709625ae6da/examples/analytics/typescript-postgres-grafana/src/server.ts#L12)):*
<details><summary><i>Previously, pkaminski (Piotr Kaminski) wrote…</i></summary><blockquote>

Do you want to check `process.env.NODE_ENV !== 'production'` instead?
</blockquote></details>

I'm not sure, actually, since `synchronize: false` only makes sense if we have migrations setup, which we don't and probably never will
___
*[`examples/analytics/typescript-postgres-grafana/src/server.ts` line 14 at r2](https://reviewable.io/reviews/Reviewable/Reviewable/1079#-NZUnTyj0Ztf63XxFL_f:-NZUnTyj0Ztf63XxFL_g:undefined) ([raw file](https://github.com/Reviewable/Reviewable/blob/111d4168cf161d428e06e4dee0005709625ae6da/examples/analytics/typescript-postgres-grafana/src/server.ts#L14)):*
> ```XML
> if (true) {  // dev-only
>   dataSourceConfig.synchronize = true;
> }
> ```





_Suggestion:_
```XML
const dataSourceConfig = {
  ...ormconfig,
  synchronize: true,
  entities: [Event, User],
};
```
___
*[`examples/analytics/typescript-postgres-grafana/src/server.ts` line 18 at r2](https://reviewable.io/reviews/Reviewable/Reviewable/1079#-NZUbxP35fOJ1g2ygtVP:-NZUnZ824UiW8GQpzCpU:bh4prz1) ([raw file](https://github.com/Reviewable/Reviewable/blob/111d4168cf161d428e06e4dee0005709625ae6da/examples/analytics/typescript-postgres-grafana/src/server.ts#L18)):*
<details><summary><i>Previously, pkaminski (Piotr Kaminski) wrote…</i></summary><blockquote>

Nit:  I'd pick either `'` (Reviewable preferred) or `"` for string delimiters and stick with it throughout, just to be easier on the eyes if nothing else.
</blockquote></details>

funnily enough, these style differences come from the 3 sources of code here: Reviewable docs, ChatGPT, and me. :D

**Review by pkaminski — COMMENTED** [review]
Oh, I thought we wanted to build this in and support a special `postgres://foo/bar` URL for `REVIEWABLE_ANALYTICS_URL`.  But if said customer is happy with a separate container then I'd just as soon not do that.

I also find it funny that you as PR author respond to comments with suggested changes.  You've been a reviewer for too long! :laughing: 

> *[Reviewable](https://reviewable.io/reviews/Reviewable/Reviewable/1079#-:-NZUoRGh7ZV4oSTIC_P-:b-q18zf5)* status: all files reviewed, 5 unresolved discussions (waiting on @fahhem)

___
*[`examples/analytics/typescript-postgres-grafana/src/server.ts` line 12 at r2](https://reviewable.io/reviews/Reviewable/Reviewable/1079#-NZUbd8F4rVJ0022Zo0y:-NZUoyyv8uy95SkcW40p:b681tid) ([raw file](https://github.com/Reviewable/Reviewable/blob/111d4168cf161d428e06e4dee0005709625ae6da/examples/analytics/typescript-postgres-grafana/src/server.ts#L12)):*
<details><summary><i>Previously, fahhem (Fahrzin Hemmati) wrote…</i></summary><blockquote>

I'm not sure, actually, since `synchronize: false` only makes sense if we have migrations setup, which we don't and probably never will
</blockquote></details>

I guess I'd at least explain a bit what this flag does, and why you might or might not wan to set it to `true`, given that this is an example and all.

**Review by fahhem — COMMENTED** [review]
I developed a habit when I used github to suggest changes, then go and accept them so I wouldn't have to mess with my local git repo if I didn't have to :D

> *[Reviewable](https://reviewable.io/reviews/Reviewable/Reviewable/1079#-:-NZUsZC93PqPV37kF6xf:b-zam266)* status: all files reviewed, 5 unresolved discussions (waiting on @pkaminski)

**Review by fahhem — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Reviewable/Reviewable/1079)* status: 7 of 12 files reviewed, 3 unresolved discussions (waiting on @pkaminski)

___
*[`examples/analytics/typescript-postgres-grafana/src/server.ts` line 12 at r2](https://reviewable.io/reviews/Reviewable/Reviewable/1079#-NZUbd8F4rVJ0022Zo0y:-NZnhZ1C0SA6g0KiTNPc:b-896fix) ([raw file](https://github.com/Reviewable/Reviewable/blob/111d4168cf161d428e06e4dee0005709625ae6da/examples/analytics/typescript-postgres-grafana/src/server.ts#L12)):*
<details><summary><i>Previously, pkaminski (Piotr Kaminski) wrote…</i></summary><blockquote>

I guess I'd at least explain a bit what this flag does, and why you might or might not wan to set it to `true`, given that this is an example and all.
</blockquote></details>

Done.

**Review by pkaminski — COMMENTED** [review]
:lgtm:

> Reviewed 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Reviewable/Reviewable/1079#-:-NZnzy3B509Ozf3M1sIa:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @fahhem)

**Pull request merged**
