### PR TITLE
Document baseChangesOnly and add a sample condition.

### PR DESCRIPTION
**Pull request by pkaminski**
This change is [Reviewable](https://reviewable.io/reviews/reviewable/reviewable/965)

### CODE REVIEW

**Comment by pkaminski** [comment]
I'll write up a Headway post and link it once I'm confident that my design is right.

**Comment by pkaminski** [comment]
+reviewer:@earlachromatic

**Review by earlAchromatic — COMMENTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/reviewable/reviewable/965)* status: all files reviewed, 2 unresolved discussions (waiting on @cgiroux86 and @pkaminski)

___
*[`docs/repositories.md` line 176 at r1](https://reviewable.io/reviews/reviewable/reviewable/965#-NDiWn0w70j51h8CT3wH:-NDiWn0w70j51h8CT3wI:b-o9mj5i) ([raw file](https://github.com/reviewable/reviewable/blob/4df359c2ddf23a531f22a4742eeb463456899f65/docs/repositories.md#L176)):*
> This can get pretty complex

Its true, but it can also be fairly simple and the tradeoff of complexity is power it grants you. Maybe restate to avoid scaring anyone away? I dunno, our users likely aren't scared of complexity but are they more or less likely to spend time on trying something if they think it will be a chore? Just my 2 cents.
___
*[`docs/repositories.md` line 330 at r1](https://reviewable.io/reviews/reviewable/reviewable/965#-NDiXlBh0FEDjODwmmsm:-NDiXlBiBoyVHMbgGzke:b4xeknh) ([raw file](https://github.com/reviewable/reviewable/blob/4df359c2ddf23a531f22a4742eeb463456899f65/docs/repositories.md#L330)):*
> ```Markdown
> The file revision properties require a bit of additional explanation.  First, renamed file matching and base change detection is performed only in clients, so the condition will get incomplete input data until a user with appropriate permissions visits the review.
> 
> Second, the `baseChangesOnly` flag is computed relative to its revision's *prior revision*, which is not necessarily the immediately preceding one.  This becomes important when rebasing multiple commits in a review following "review each commit" style, as Reviewable will do its best to match up each "new" commit to its semantic antecedent.  We don't surface these details in the data structure above but our algorithm is fairly robust and biased towards needing strong evidence for a match so false positive `baseChangesOnly` flags should be extremely rare.
> ```

Should users really have to think about prior revisions vs previous ones to use `baseChangesOnly` flag effectively in completion conditions? 

I think it should be a safe assumption for the user that the flag will choose the right revs to look at and *just work*. In my mind the risk is just confusing people and I think the goal of docs should be clarity. I am on the fence whether the second paragraph is really necessary.

**Review by pkaminski — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/reviewable/reviewable/965)* status: 1 of 3 files reviewed, 2 unresolved discussions (waiting on @cgiroux86 and @earlAchromatic)

___
*[`docs/repositories.md` line 176 at r1](https://reviewable.io/reviews/reviewable/reviewable/965#-NDiWn0w70j51h8CT3wH:-NElyK7m5wvbahUX4FbG:b-wrypt6) ([raw file](https://github.com/reviewable/reviewable/blob/4df359c2ddf23a531f22a4742eeb463456899f65/docs/repositories.md#L176)):*
<details><summary><i>Previously, earlAchromatic (Jacob Milhorn) wrote…</i></summary><blockquote>

> This can get pretty complex

Its true, but it can also be fairly simple and the tradeoff of complexity is power it grants you. Maybe restate to avoid scaring anyone away? I dunno, our users likely aren't scared of complexity but are they more or less likely to spend time on trying something if they think it will be a chore? Just my 2 cents.
</blockquote></details>

Tweaked the language; trying to go for a "easy to get started but sky's the limit" vibe.
___
*[`docs/repositories.md` line 330 at r1](https://reviewable.io/reviews/reviewable/reviewable/965#-NDiXlBh0FEDjODwmmsm:-NElyeDT3dGQKvn7HSZw:b-37le7i) ([raw file](https://github.com/reviewable/reviewable/blob/4df359c2ddf23a531f22a4742eeb463456899f65/docs/repositories.md#L330)):*
<details><summary><i>Previously, earlAchromatic (Jacob Milhorn) wrote…</i></summary><blockquote>

Should users really have to think about prior revisions vs previous ones to use `baseChangesOnly` flag effectively in completion conditions? 

I think it should be a safe assumption for the user that the flag will choose the right revs to look at and *just work*. In my mind the risk is just confusing people and I think the goal of docs should be clarity. I am on the fence whether the second paragraph is really necessary.
</blockquote></details>

I think if users will rely on the flag to potentially skip reviews then it's important that they know *exactly* what it means and what are its limitations.  This part of the docs is aimed at admins so I think it's fair to get a bit more technical.

**Review by earlAchromatic — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/reviewable/reviewable/965#-:-NEmjkT2BDQWO25Z8rGA:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @cgiroux86 and @pkaminski)

___
*[`docs/repositories.md` line 176 at r1](https://reviewable.io/reviews/reviewable/reviewable/965#-NDiWn0w70j51h8CT3wH:-NEmimIg94nWVLEwnvSt:b-e9fh2v) ([raw file](https://github.com/reviewable/reviewable/blob/4df359c2ddf23a531f22a4742eeb463456899f65/docs/repositories.md#L176)):*
<details><summary><i>Previously, pkaminski (Piotr Kaminski) wrote…</i></summary><blockquote>

Tweaked the language; trying to go for a "easy to get started but sky's the limit" vibe.
</blockquote></details>

I like the way this reads. I think you achieved what you are going for 👍

**Review by pkaminski — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/reviewable/reviewable/965)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @cgiroux86)

**Review by pkaminski — COMMENTED** [review]
> Reviewed 1 of 3 files at r1, 1 of 2 files at r2, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/reviewable/reviewable/965)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @cgiroux86)

**Pull request merged**
