### PR TITLE
Add documentation for REST API

### PR DESCRIPTION
**Pull request by snoack**
This change is [Reviewable](https://reviewable.io/reviews/Reviewable/Reviewable/1132)

### CODE REVIEW

**Review by pkaminski — COMMENTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Reviewable/Reviewable/1132)* status: all files reviewed, 4 unresolved discussions (waiting on @snoack)

___
*[`enterprise/api.md` line 54 at r1](https://reviewable.io/reviews/Reviewable/Reviewable/1132#-NoTTYAm50UVaSI7naup:-NoTTYAm50UVaSI7nauq:b-z1nevh) ([raw file](https://github.com/Reviewable/Reviewable/blob/3cf6cff959c9246a8760edb3dd74aaaaa67ed553/enterprise/api.md#L54)):*
> ```Markdown
> ###### `guests`: array of occupant objects
> 
> The users that occupy a guest seat.
> ```

"These don't count towards the licensed seats."
___
*[`enterprise/api.md` line 64 at r1](https://reviewable.io/reviews/Reviewable/Reviewable/1132#-NoTTHSp2trg2ZgaKUUb:-NoTTHSp2trg2ZgaKUUc:b-54juxh) ([raw file](https://github.com/Reviewable/Reviewable/blob/3cf6cff959c9246a8760edb3dd74aaaaa67ed553/enterprise/api.md#L64)):*
> ```Markdown
> ###### `last_activity`: ISO date and time string
> 
> Time at which the user most recently performed an action that requires to be covered by a license
> ```

delete "to be covered by", add a comma after "license"
___
*[`enterprise/api.md` line 123 at r1](https://reviewable.io/reviews/Reviewable/Reviewable/1132#-NoTTujD65RlcyK3ahbT:-NoTTujD65RlcyK3ahbU:undefined) ([raw file](https://github.com/Reviewable/Reviewable/blob/3cf6cff959c9246a8760edb3dd74aaaaa67ed553/enterprise/api.md#L123)):*
> ```Markdown
>         "name":"Sebastian Noack"
>       } */
>     }
> ```





_Suggestion:_
```Markdown
    {
      "github_id": 1646896,
      "last_activity": "2023-12-05T05:57:23.902Z",
      "session_end": "2024-03-04T05:57:23.902Z",
      /* expand=guests.details
      "details": {
        "email":"piotr@reviewable.io",
        "username":"pkaminski",
        "name":"Piotr Kaminski"
      } */
    }
```
___
*[`enterprise/config.md` line 79 at r1](https://reviewable.io/reviews/Reviewable/Reviewable/1132#-NoTRgbA5oKqkPO2FuYt:-NoTRgbA5oKqkPO2FuYu:bj3yftt) ([raw file](https://github.com/Reviewable/Reviewable/blob/3cf6cff959c9246a8760edb3dd74aaaaa67ed553/enterprise/config.md#L79)):*
> ```Markdown
> * `REVIEWABLE_STRICT_TRANSPORT_SECURITY`: The value of the `Strict-Transport-Security` header in all responses.  For example, set to `max-age=31536000` to enforce secure connections to `REVIEWABLE_HOST_URL` for at least a year.
> * `NODE_EXTRA_CA_CERTS`: The absolute path to a cert file in PEM format; this might be your GHE instance's SSL cert, or the root cert for your organization.  Useful if your GitHub installation uses a self-signed (or otherwise non-validating) certificate, as otherwise Reviewable will refuse to connect to the API with errors like "unable to get local issuer certificate".  This environment variable **must be set directly**, not via the `REVIEWABLE_CONFIG_FILE` file.
> * `REVIEWABLE_API_SECRET`: A secret token (ASCII only) used to authentificate requests to the [REST API](https://github.com/Reviewable/Reviewable/blob/master/enterprise/api.md). If unset the REST API will be disabled.
> ```

authentificate -> authenticate

**Review by snoack — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Reviewable/Reviewable/1132)* status: all files reviewed, 2 unresolved discussions (waiting on @pkaminski)

___
*[`enterprise/api.md` line 54 at r1](https://reviewable.io/reviews/Reviewable/Reviewable/1132#-NoTTYAm50UVaSI7naup:-NoTWXWABeh17x6ue4yW:b-896fix) ([raw file](https://github.com/Reviewable/Reviewable/blob/3cf6cff959c9246a8760edb3dd74aaaaa67ed553/enterprise/api.md#L54)):*
<details><summary><i>Previously, pkaminski (Piotr Kaminski) wrote…</i></summary><blockquote>

"These don't count towards the licensed seats."
</blockquote></details>

Done.
___
*[`enterprise/api.md` line 64 at r1](https://reviewable.io/reviews/Reviewable/Reviewable/1132#-NoTTHSp2trg2ZgaKUUb:-NoTWMio1EqrRSry4tM0:b-896fix) ([raw file](https://github.com/Reviewable/Reviewable/blob/3cf6cff959c9246a8760edb3dd74aaaaa67ed553/enterprise/api.md#L64)):*
<details><summary><i>Previously, pkaminski (Piotr Kaminski) wrote…</i></summary><blockquote>

delete "to be covered by", add a comma after "license"
</blockquote></details>

Done.
___
*[`enterprise/api.md` line 123 at r1](https://reviewable.io/reviews/Reviewable/Reviewable/1132#-NoTTujD65RlcyK3ahbT:-NoTWF7H0mbzVQC-BRSi:b-896fix) ([raw file](https://github.com/Reviewable/Reviewable/blob/3cf6cff959c9246a8760edb3dd74aaaaa67ed553/enterprise/api.md#L123)):*
> ```Markdown
>         "name":"Sebastian Noack"
>       } */
>     }
> ```

Done.
___
*[`enterprise/config.md` line 79 at r1](https://reviewable.io/reviews/Reviewable/Reviewable/1132#-NoTRgbA5oKqkPO2FuYt:-NoTXC0cBfI_6doHRrB9:b-896fix) ([raw file](https://github.com/Reviewable/Reviewable/blob/3cf6cff959c9246a8760edb3dd74aaaaa67ed553/enterprise/config.md#L79)):*
<details><summary><i>Previously, pkaminski (Piotr Kaminski) wrote…</i></summary><blockquote>

authentificate -> authenticate
</blockquote></details>

Done.

**Review by pkaminski — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Reviewable/Reviewable/1132)* status: all files reviewed, 1 unresolved discussion (waiting on @snoack)

___
*[`enterprise/api.md` line 33 at r2](https://reviewable.io/reviews/Reviewable/Reviewable/1132#-NoU-T0J8A4o4dZ7vKI9:-NoU-T0K64Sp6AFWBEkq:b-7fjm3a) ([raw file](https://github.com/Reviewable/Reviewable/blob/d3d2d58787558ff626693bee399b51e91da38066/enterprise/api.md#L33)):*
> ```Markdown
> | `num_seats`          | number                      | The number of seats.          |
> | `num_occupied_seats` | number                      | The number of seats occupied. |
> | `expiry`             | ISO date and time string    | Time at which this license.   |
> ```

...will expire.
___
*[`enterprise/config.md` line 79 at r1](https://reviewable.io/reviews/Reviewable/Reviewable/1132#-NoTRgbA5oKqkPO2FuYt:-NoU-mAY4opqdUJAcWuC:b-a1qkra) ([raw file](https://github.com/Reviewable/Reviewable/blob/3cf6cff959c9246a8760edb3dd74aaaaa67ed553/enterprise/config.md#L79)):*
<details><summary><i>Previously, snoack (Sebastian Noack) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not saved?

**Review by snoack — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Reviewable/Reviewable/1132)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @pkaminski)

___
*[`enterprise/api.md` line 33 at r2](https://reviewable.io/reviews/Reviewable/Reviewable/1132#-NoU-T0J8A4o4dZ7vKI9:-NoU2MEgC7Sq6eSRMCH7:b-896fix) ([raw file](https://github.com/Reviewable/Reviewable/blob/d3d2d58787558ff626693bee399b51e91da38066/enterprise/api.md#L33)):*
<details><summary><i>Previously, pkaminski (Piotr Kaminski) wrote…</i></summary><blockquote>

...will expire.
</blockquote></details>

Done.
___
*[`enterprise/config.md` line 79 at r1](https://reviewable.io/reviews/Reviewable/Reviewable/1132#-NoTRgbA5oKqkPO2FuYt:-NoU1ey_3uGMdgquGn8l:b-l0isnd) ([raw file](https://github.com/Reviewable/Reviewable/blob/3cf6cff959c9246a8760edb3dd74aaaaa67ed553/enterprise/config.md#L79)):*
<details><summary><i>Previously, pkaminski (Piotr Kaminski) wrote…</i></summary><blockquote>

Not saved?
</blockquote></details>

It turned out I fixed the same typo somewhere else instead (see diff r1 -> r2). Fixed here as well now.

**Review by pkaminski — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Reviewable/Reviewable/1132#-:-NoU3_ST7EcPylSTY8nl:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @snoack)

**Comment by pkaminski** [comment]
Let's wait before merging, though, until the API feature is released.

**Review by pkaminski — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Reviewable/Reviewable/1132)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @snoack)

**Pull request merged**
