### PR TITLE
Add docs for new webhook payload data

### PR DESCRIPTION
**Pull request by fahhem**
This change is [Reviewable](https://reviewable.io/reviews/Reviewable/Reviewable/1029)

### CODE REVIEW

**Review by pkaminski — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Reviewable/Reviewable/1029)* status: all files reviewed, 3 unresolved discussions (waiting on @fahhem)

___
*[`docs/repositories.md` line 367 at r1](https://reviewable.io/reviews/Reviewable/Reviewable/1029#-NRarQAe794_56F5H824:-NRarQAe794_56F5H825:b-bw1hg8) ([raw file](https://github.com/Reviewable/Reviewable/blob/6e40901d1b5e965bf58745cafb74e94e8cafa4f7/docs/repositories.md#L367)):*
> ```Markdown
> ```js
> {
>   // for Slack, this is technically Markdown: https://www.markdownguide.org/tools/slack/
> ```

"technically" is doing a lot heavy lifting there!  :)  I'd say it's Markdown-inspired, or perhaps Markdown-flavored, but it certainly ain't Markdown.
___
*[`docs/repositories.md` line 380 at r1](https://reviewable.io/reviews/Reviewable/Reviewable/1029#-NRarv127mDFkM19IFHW:-NRarv127mDFkM19IFHX:bn85dmb) ([raw file](https://github.com/Reviewable/Reviewable/blob/6e40901d1b5e965bf58745cafb74e94e8cafa4f7/docs/repositories.md#L380)):*
> ```Markdown
>   "key": "Reviewable/demo/1",  // you can use this identifier for threading
>   
>   // The following is meant for more customized workflows, so feel free to mix-and-match here and above:
> ```

The `body` section is meant to complement the `subject`, and while it says "for email gateways" above it's really for any system that splits up the subject from the body.
___
*[`docs/repositories.md` line 387 at r1](https://reviewable.io/reviews/Reviewable/Reviewable/1029#-NRasFRt-9l9AOt5J0u3:-NRasFRt-9l9AOt5J0u4:bpf1yh) ([raw file](https://github.com/Reviewable/Reviewable/blob/6e40901d1b5e965bf58745cafb74e94e8cafa4f7/docs/repositories.md#L387)):*
> ```Markdown
>     "markdown": "Review in progress: 1 of 4 files reviewed, 2 unresolved discussions  \nWaiting on: **fahhem**"
>   },
>   // And now the ultimate in customizability:
> ```

I just noticed that this doesn't include the description proper (which could be anything, as it's generated by the completion condition), so you can't actually rebuild the messages above using just this data.
___
*[`docs/repositories.md` line 392 at r1](https://reviewable.io/reviews/Reviewable/Reviewable/1029#-NRasXo05oMcG5BBjej2:-NRasXo05oMcG5BBjej3:b-wbd9k) ([raw file](https://github.com/Reviewable/Reviewable/blob/6e40901d1b5e965bf58745cafb74e94e8cafa4f7/docs/repositories.md#L392)):*
> ```Markdown
>   "data": {
>     "pullRequest": {
>       "number": 1,
> ```

Nit: strange ordering of properties; I'd put `number` after `repository` for better readability.

**Review by fahhem — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Reviewable/Reviewable/1029)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @fahhem)

___
*[`docs/repositories.md` line 387 at r1](https://reviewable.io/reviews/Reviewable/Reviewable/1029#-NRasFRt-9l9AOt5J0u3:-NRauHVN5GWMj6-Iz6KI:b-er83sg) ([raw file](https://github.com/Reviewable/Reviewable/blob/6e40901d1b5e965bf58745cafb74e94e8cafa4f7/docs/repositories.md#L387)):*
<details><summary><i>Previously, pkaminski (Piotr Kaminski) wrote…</i></summary><blockquote>

I just noticed that this doesn't include the description proper (which could be anything, as it's generated by the completion condition), so you can't actually rebuild the messages above using just this data.
</blockquote></details>

What do you mean the "description proper"? Is that different from the pullRequest's description?

**Review by pkaminski — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Reviewable/Reviewable/1029)* status: all files reviewed, 1 unresolved discussion (waiting on @fahhem)

___
*[`docs/repositories.md` line 387 at r1](https://reviewable.io/reviews/Reviewable/Reviewable/1029#-NRasFRt-9l9AOt5J0u3:-NRavla_EJRAbhmsPol-:b-euxpl6) ([raw file](https://github.com/Reviewable/Reviewable/blob/6e40901d1b5e965bf58745cafb74e94e8cafa4f7/docs/repositories.md#L387)):*
<details><summary><i>Previously, fahhem (Fahrzin Hemmati) wrote…</i></summary><blockquote>

What do you mean the "description proper"? Is that different from the pullRequest's description?
</blockquote></details>

Yeah, I mean the review state description, e.g., `1 of 4 files reviewed, 2 unresolved discussions`.
___
*[`docs/repositories.md` line 384 at r2](https://reviewable.io/reviews/Reviewable/Reviewable/1029#-NRavUTt9F4CS5k6i7lm:-NRavUTt9F4CS5k6i7ln:b5agexv) ([raw file](https://github.com/Reviewable/Reviewable/blob/8632b894c0664209ff41c12c5a96f811fbc8b721/docs/repositories.md#L384)):*
> ```Markdown
>     "text": "<https://reviewable.io/reviews/reviewable/demo/1|*Review in progress: 1 of 4 files reviewed, 2 unresolved discussions*>\nWaiting on: *pkaminski*",
>     "plainText": "Review in progress: 1 of 4 files reviewed, 2 unresolved discussions\nWaiting on: pkaminski",
>     "html": "Review in progress: 1 of 4 files reviewed, 2 unresolved discussions\n<br>Waiting on: <b>pkaminski</b>",
> ```

I didn't notice on the first pass, but shouldn't this match the `htmlBody` above?  And `markdown` below puts a link on the "review in progress" as well.

**Review by fahhem — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Reviewable/Reviewable/1029)* status: all files reviewed, 1 unresolved discussion (waiting on @pkaminski)

___
*[`docs/repositories.md` line 387 at r1](https://reviewable.io/reviews/Reviewable/Reviewable/1029#-NRasFRt-9l9AOt5J0u3:-NRaw7-yBPWxomkKMaYP:bdi3kn6) ([raw file](https://github.com/Reviewable/Reviewable/blob/6e40901d1b5e965bf58745cafb74e94e8cafa4f7/docs/repositories.md#L387)):*
<details><summary><i>Previously, pkaminski (Piotr Kaminski) wrote…</i></summary><blockquote>

Yeah, I mean the review state description, e.g., `1 of 4 files reviewed, 2 unresolved discussions`.
</blockquote></details>

Ah, so we can add something about reviewed/unreviewed files and open discussions in the future
___
*[`docs/repositories.md` line 384 at r2](https://reviewable.io/reviews/Reviewable/Reviewable/1029#-NRavUTt9F4CS5k6i7lm:-NRaw0t53NFQGRXt9ydb:b6fvrg9) ([raw file](https://github.com/Reviewable/Reviewable/blob/8632b894c0664209ff41c12c5a96f811fbc8b721/docs/repositories.md#L384)):*
<details><summary><i>Previously, pkaminski (Piotr Kaminski) wrote…</i></summary><blockquote>

I didn't notice on the first pass, but shouldn't this match the `htmlBody` above?  And `markdown` below puts a link on the "review in progress" as well.
</blockquote></details>

I tried to rebuild this from make's output, so it should be based on what actually happens. I didn't do it based on the code

**Comment by pkaminski** [comment]
*[`docs/repositories.md` line 384 at r2](https://reviewable.io/reviews/Reviewable/Reviewable/1029#-NRavUTt9F4CS5k6i7lm:-NRawrpADhQ4ZyC8DaO6:bdcrd87) ([raw file](https://github.com/Reviewable/Reviewable/blob/8632b894c0664209ff41c12c5a96f811fbc8b721/docs/repositories.md#L384)):*
<details><summary><i>Previously, fahhem (Fahrzin Hemmati) wrote…</i></summary><blockquote>

I tried to rebuild this from make's output, so it should be based on what actually happens. I didn't do it based on the code
</blockquote></details>

Make shows the links in `body` properties:

**Review by pkaminski — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Reviewable/Reviewable/1029)* status: all files reviewed, 1 unresolved discussion (waiting on @fahhem)

___
*[`docs/repositories.md` line 387 at r1](https://reviewable.io/reviews/Reviewable/Reviewable/1029#-NRasFRt-9l9AOt5J0u3:-NRaxV4d6kXp37DwI4df:b-smobx3) ([raw file](https://github.com/Reviewable/Reviewable/blob/6e40901d1b5e965bf58745cafb74e94e8cafa4f7/docs/repositories.md#L387)):*
<details><summary><i>Previously, fahhem (Fahrzin Hemmati) wrote…</i></summary><blockquote>

Ah, so we can add something about reviewed/unreviewed files and open discussions in the future
</blockquote></details>

No, we need to literally put in the description text, as it's custom-generated by the condition.  (We can _also_ put in various counters, but there's no guarantee you can use them to generate the actual description.)

**Review by fahhem — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Reviewable/Reviewable/1029)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @fahhem)

___
*[`docs/repositories.md` line 387 at r1](https://reviewable.io/reviews/Reviewable/Reviewable/1029#-NRasFRt-9l9AOt5J0u3:-NRay38L3bXH6wCILvfJ:b-wdr3uk) ([raw file](https://github.com/Reviewable/Reviewable/blob/6e40901d1b5e965bf58745cafb74e94e8cafa4f7/docs/repositories.md#L387)):*
<details><summary><i>Previously, pkaminski (Piotr Kaminski) wrote…</i></summary><blockquote>

No, we need to literally put in the description text, as it's custom-generated by the condition.  (We can _also_ put in various counters, but there's no guarantee you can use them to generate the actual description.)
</blockquote></details>

Ohh, okay, will open a PR for that in a bit

**Review by pkaminski — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Reviewable/Reviewable/1029#-:-NRazOyuExvZxcy3vcnS:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @fahhem)

**Pull request merged**
