### PR TITLE
new overlap strategy section in docs

### PR DESCRIPTION
**Pull request by anthonykawa**
This change is [Reviewable](https://reviewable.io/reviews/reviewable/reviewable/831)

### CODE REVIEW

**Review by pkaminski — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/reviewable/reviewable/831)* status: all files reviewed, 5 unresolved discussions (waiting on @anthonykawa)

___
*[docs/reviews.md, line 191 at r1](https://reviewable.io/reviews/reviewable/reviewable/831#-MZRkP_t4x8LQltJu76S:-MZRkP_t4x8LQltJu76T:b-ryg048) ([raw file](https://github.com/reviewable/reviewable/blob/58a19492231aa0054b2e80fc6a8cff5eeda3a363/docs/reviews.md#L191)):*
> ```Markdown
> When applicable, you’ll find a small **Show full diff** link beneath the **Show Unreviewed Diffs** button that will show the full diffs between the base and the latest revision for each file.  This will show you exactly the full deltas that will be applied if the PR is merged.
> 
> When appropriate, a checkbox for **Include changes in files previously reviewed only by others** will appears beneath the button. Leave this box unchecked to automatically partition a review among multiple reviewers. For each file, Reviewable finds the last reviewed revision, then considers everyone who reviewed it to be a reviewer of that file. <more> So if Peter reviews a file at r1, and then John force-reviews it at r2, then John becomes a reviewer of that file and — by default — it won't get diffed for Peter. The exact semantics of this feature are a bit tricky, though, so please see [issue #404](https://github.com/Reviewable/Reviewable/issues/404) for a full exploration and why some people choose to remap `n/p` onto <code>nextPersonallyUnreviewedFile()</code>.</more>
> ```

I think it would be useful to keep the old example for 'unclaimed' in the docs.  This kind of detail is precisely what the docs are for, otherwise we'd just stick with the contextual help...
___
*[docs/reviews.md, line 193 at r1](https://reviewable.io/reviews/reviewable/reviewable/831#-MZRj9qnDwPO39eZoKS5:-MZRj9qnDwPO39eZoKS6:bival2r) ([raw file](https://github.com/reviewable/reviewable/blob/f78000d67749b62c7476522be67866ca49018a74/docs/reviews.md#L193)):*
> ```Markdown
> 
> 
> When appropriate, a dropdown with three **review overlap strategy** options will appear beneath the button. This setting changes how the reviews are suggested for the user to review and implicitly sets the default for any future reviews.
> ```

how the reviews -> which file diffs
___
*[docs/reviews.md, line 195 at r1](https://reviewable.io/reviews/reviewable/reviewable/831#-MZRjlz-1Fzwk2KCHmiy:-MZRjlz-1Fzwk2KCHmiz:b-67nq6r) ([raw file](https://github.com/reviewable/reviewable/blob/f78000d67749b62c7476522be67866ca49018a74/docs/reviews.md#L195)):*
> ```Markdown
> When appropriate, a dropdown with three **review overlap strategy** options will appear beneath the button. This setting changes how the reviews are suggested for the user to review and implicitly sets the default for any future reviews.
> 
> reviewable summary of images
> ```

You need to update the overall Changes panel screenshot above, and once you do that then I don't think this new screenshot adds anything.  (Instead of setting up the shot from scratch, you may be able to apply some Photoshop-fu and patch the new dropdown into the old shot.  I'm OK with that as long as it looks reasonably cohesive.)
___
*[docs/reviews.md, line 197 at r1](https://reviewable.io/reviews/reviewable/reviewable/831#-MZRkidN2-_9AQ9FR5Tv:-MZRkidN2-_9AQ9FR5Tw:b4z0mrw) ([raw file](https://github.com/reviewable/reviewable/blob/f78000d67749b62c7476522be67866ca49018a74/docs/reviews.md#L197)):*
> ```Markdown
> reviewable summary of images
> 
> - **Skip files claimed by others** suggests files that have not been reviewed by others in current and previous revisions.
> ```

in -> at
___
*[docs/reviews.md, line 198 at r1](https://reviewable.io/reviews/reviewable/reviewable/831#-MZRkwNv66BIur2Ntfnd:-MZRkwNv66BIur2Ntfne:b6bd83n) ([raw file](https://github.com/reviewable/reviewable/blob/f78000d67749b62c7476522be67866ca49018a74/docs/reviews.md#L198)):*
> ```Markdown
> 
> - **Skip files claimed by others** suggests files that have not been reviewed by others in current and previous revisions.
> - **Review any unreviewed files** suggests files to review if they have not been reviewed by others within the current revision.
> ```

by others within -> by anyone at

**Review by anthonykawa — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/reviewable/reviewable/831)* status: all files reviewed, 5 unresolved discussions (waiting on @anthonykawa and @pkaminski)

___
*[docs/reviews.md, line 191 at r1](https://reviewable.io/reviews/reviewable/reviewable/831#-MZRkP_t4x8LQltJu76S:-MZTSG6A1YEOuGsVva9-:bss63s9) ([raw file](https://github.com/reviewable/reviewable/blob/58a19492231aa0054b2e80fc6a8cff5eeda3a363/docs/reviews.md#L191)):*
I just want to confirm. Are you referring to this part?
> For each file, Reviewable finds the last reviewed revision, then considers everyone who reviewed it to be a reviewer of that file. So if Peter reviews a file at r1, and then John force-reviews it at r2, then John becomes a reviewer of that file and — by default — it won't get diffed for Peter.

**Review by anthonykawa — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/reviewable/reviewable/831)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @pkaminski)

___
*[docs/reviews.md, line 195 at r1](https://reviewable.io/reviews/reviewable/reviewable/831#-MZRjlz-1Fzwk2KCHmiy:-MZU3cCN4n1zkKAJ-BlO:b-896fix) ([raw file](https://github.com/reviewable/reviewable/blob/f78000d67749b62c7476522be67866ca49018a74/docs/reviews.md#L195)):*
<details><summary><i>Previously, pkaminski (Piotr Kaminski) wrote…</i></summary><blockquote>

You need to update the overall Changes panel screenshot above, and once you do that then I don't think this new screenshot adds anything.  (Instead of setting up the shot from scratch, you may be able to apply some Photoshop-fu and patch the new dropdown into the old shot.  I'm OK with that as long as it looks reasonably cohesive.)
</blockquote></details>

Done.

**Review by anthonykawa — COMMENTED** [review]
PTAL

> *[Reviewable](https://reviewable.io/reviews/reviewable/reviewable/831#-:-MZaMcWT3UMdknNWBIZW:bb71pro)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @pkaminski)

**Review by pkaminski — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/reviewable/reviewable/831)* status: all files reviewed, 1 unresolved discussion (waiting on @anthonykawa)

___
*[docs/reviews.md, line 191 at r1](https://reviewable.io/reviews/reviewable/reviewable/831#-MZRkP_t4x8LQltJu76S:-MZhcMtE0Ns_su3icBqk:b2318ar) ([raw file](https://github.com/reviewable/reviewable/blob/58a19492231aa0054b2e80fc6a8cff5eeda3a363/docs/reviews.md#L191)):*
<details><summary><i>Previously, anthonykawa (Anthony Kawa) wrote…</i></summary><blockquote>

I just want to confirm. Are you referring to this part?
> For each file, Reviewable finds the last reviewed revision, then considers everyone who reviewed it to be a reviewer of that file. So if Peter reviews a file at r1, and then John force-reviews it at r2, then John becomes a reviewer of that file and — by default — it won't get diffed for Peter.
</blockquote></details>

Yes, but this applies only to the `unclaimed` strategy, and the last bit about `nextPersonallyUnreviewedFile()` is no longer relevant as you removed that code.  I think the extract you quoted above is just right for adding to the `unclaimed` bullet point.

I'd also include the "why you might want to use this strategy" blurbs from the dropdown itself, and anything that shows up in contextual help.  Basically, the docs should be a superset of all the other information sources.

**Review by anthonykawa — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/reviewable/reviewable/831)* status: 2 of 4 files reviewed, 1 unresolved discussion (waiting on @pkaminski)

___
*[docs/reviews.md, line 191 at r1](https://reviewable.io/reviews/reviewable/reviewable/831#-MZRkP_t4x8LQltJu76S:-MZrlIHfCALYwmysEIPF:b7slqyu) ([raw file](https://github.com/reviewable/reviewable/blob/58a19492231aa0054b2e80fc6a8cff5eeda3a363/docs/reviews.md#L191)):*
<details><summary><i>Previously, pkaminski (Piotr Kaminski) wrote…</i></summary><blockquote>

Yes, but this applies only to the `unclaimed` strategy, and the last bit about `nextPersonallyUnreviewedFile()` is no longer relevant as you removed that code.  I think the extract you quoted above is just right for adding to the `unclaimed` bullet point.

I'd also include the "why you might want to use this strategy" blurbs from the dropdown itself, and anything that shows up in contextual help.  Basically, the docs should be a superset of all the other information sources.
</blockquote></details>

I've included the wording from the dropdown and the contextual help. I'm still getting acquainted with the way to display the information but I thought the section about still being "able to manually diff every file" would make sense as a tip. Thoughts?

**Review by anthonykawa — COMMENTED** [review]
I'm wondering how Chris's commit showed up in my review. 

> *[Reviewable](https://reviewable.io/reviews/reviewable/reviewable/831#-:-MZrmHc0ATD9X6IHjRzv:b-ukt8pb)* status: 2 of 4 files reviewed, 1 unresolved discussion (waiting on @pkaminski)

**Review by pkaminski — COMMENTED** [review]
Probably some sus merging or rebasing.  Gotta get that sorted out.  :)

> Reviewed 1 of 1 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/reviewable/reviewable/831#-:-MZsL6g35qL7rOAFxacT:bvcm7ew)* status: all files reviewed, 1 unresolved discussion (waiting on @anthonykawa)

*[a discussion](https://reviewable.io/reviews/reviewable/reviewable/831#-MZsLoMID8-43lVm6CSD:-MZsLoMID8-43lVm6CSE:b-r54s8k) (no related file):*
Just need to sort out your commit history, as we don't want to apply Chris's changes (again?) through this PR.

---
___
*[docs/reviews.md, line 191 at r1](https://reviewable.io/reviews/reviewable/reviewable/831#-MZRkP_t4x8LQltJu76S:-MZsLhlH30NLipCQgg1_:b-oz8tym) ([raw file](https://github.com/reviewable/reviewable/blob/58a19492231aa0054b2e80fc6a8cff5eeda3a363/docs/reviews.md#L191)):*
<details><summary><i>Previously, anthonykawa (Anthony Kawa) wrote…</i></summary><blockquote>

I've included the wording from the dropdown and the contextual help. I'm still getting acquainted with the way to display the information but I thought the section about still being "able to manually diff every file" would make sense as a tip. Thoughts?
</blockquote></details>

Good call.

**Review by anthonykawa — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/reviewable/reviewable/831)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @pkaminski)

*[a discussion](https://reviewable.io/reviews/reviewable/reviewable/831#-MZsLoMID8-43lVm6CSD:-M_0AkyO8hK8TAK6YAmM:b-896fix) (no related file):*
<details><summary><i>Previously, pkaminski (Piotr Kaminski) wrote…</i></summary><blockquote>

Just need to sort out your commit history, as we don't want to apply Chris's changes (again?) through this PR.
</blockquote></details>

Done.

---

**Review by pkaminski — COMMENTED** [review]
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/reviewable/reviewable/831)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @anthonykawa)

**Pull request merged**
