### PR TITLE
Update docs

### PR DESCRIPTION
**Pull request by cgiroux86**
update docs with deferring info and update changelog to include deferring and commit file reviewing

---
This change is [Reviewable](https://reviewable.io/reviews/reviewable/reviewable/846)

### CODE REVIEW

**Review by cgiroux86 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/reviewable/reviewable/846)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @pkaminski)

___
*[—◯— commits, line 2 at r1](https://reviewable.io/reviews/reviewable/reviewable/846#-MdX_19a7CI99KCalXJn:-MdX_19b6E6pb1Uwo2Ni:b-tnp680) ([raw file](https://github.com/reviewable/reviewable/blob/10c8eba2be798ef7e502ddee0b9edf30d97e16b6/—◯— commits#L2)):*
Test comment to see if it will repro the issue with the linemap :)

**Review by pkaminski — COMMENTED** [review]
> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/reviewable/reviewable/846)* status: all files reviewed, 3 unresolved discussions (waiting on @cgiroux86)

___
*[docs/reviews.md, line 238 at r1](https://reviewable.io/reviews/reviewable/reviewable/846#-Md_LbxS3EZ3fI9f8Fpv:-Md_LbxTCfWc5Ef6utdE:bmxfnus) ([raw file](https://github.com/reviewable/reviewable/blob/10c8eba2be798ef7e502ddee0b9edf30d97e16b6/docs/reviews.md#L238)):*
I think you should approach this more from a user's experience point of view, rather than the definitions and algorithms that we think about during implementation.  (We also generally reserve bold text for referencing UI elements or concepts.)  I'd use an approach of what -> why -> how, perhaps along these lines:

> When you publish a review and you have files left to review or discussions left to reply (red counters), the review will be automatically *deferred* for you:  the red counters will turn grey with a red outline and the review will not be awaiting your action.  This lets you post a partial review &mdash; perhaps requesting some larger design changes or putting off reviewing test cases &mdash; and visibly hand off responsibility for taking the next action.
>
> `reviewable deferral dashboard`
>
> A review will remain deferred until either a new revision of a file becomes available for you to review or a new comment is posted.  When this happens, the review will be reactivated for you with all counters going back to being red (including for files or discussions you had deferred), and the review awaiting your action once more.
> 
> Note that you can continue manipulating a review as usual while it's deferred, except that Reviewable won't suggest the next set of diffs to review.  If you wish, you can also reactivate a deferred review manually by clicking the **continue review now** button on the review page.
>
> `reviewable deferral changes`
>
> {:tip}
> Sending an individual comment (via its dedicated send button) doesn't affect deferrals either way:  it will neither defer a review, nor cause a deferred review to become active again.
___
*[enterprise/changelog.md, line 14 at r1](https://reviewable.io/reviews/reviewable/reviewable/846#-Md_EyEmCcgel6-jVUZL:-Md_EyEmCcgel6-jVUZM:bmpyph9) ([raw file](https://github.com/reviewable/reviewable/blob/10c8eba2be798ef7e502ddee0b9edf30d97e16b6/enterprise/changelog.md#L14)):*
> ```Markdown
> - Fix: consistently insert selected text when replying to a discussion.
> - New: allow reviewers to `defer` a review when they want to default to others to act before proceeding.
> - New: inject a synthetic `commitFile` to provide a place to review and comment on commit messages.
> ```

Please don't add this to the changelog until we remove the gating (and hence make the feature available to Enterprise customers).

**Review by pkaminski — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/reviewable/reviewable/846)* status: all files reviewed, 4 unresolved discussions (waiting on @cgiroux86)

*[a discussion](https://reviewable.io/reviews/reviewable/reviewable/846#-MdcyceX12YkaC--jX7i:-MdcyceY5jYS1c2LEnCl:b8skmdp) (no related file):*
Oh, you also need to update the completion condition docs.  We now pass in `deferringReviewers` as part of the review state, and also need to document our backwards compatibility logic for when we'll force-remove deferring reviewers from your condition's `pendingReviewers` output.

---

**Review by cgiroux86 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/reviewable/reviewable/846)* status: 3 of 7 files reviewed, 3 unresolved discussions (waiting on @pkaminski)

*[a discussion](https://reviewable.io/reviews/reviewable/reviewable/846#-MdcyceX12YkaC--jX7i:-MdrGXmqAn3oG4fNE2rT:b-896fix) (no related file):*
<details><summary><i>Previously, pkaminski (Piotr Kaminski) wrote…</i></summary><blockquote>

Oh, you also need to update the completion condition docs.  We now pass in `deferringReviewers` as part of the review state, and also need to document our backwards compatibility logic for when we'll force-remove deferring reviewers from your condition's `pendingReviewers` output.
</blockquote></details>

Done.

---
___
*[docs/reviews.md, line 238 at r1](https://reviewable.io/reviews/reviewable/reviewable/846#-Md_LbxS3EZ3fI9f8Fpv:-MdrJV7YD3F-IGkbyrDc:bs7wumb) ([raw file](https://github.com/reviewable/reviewable/blob/10c8eba2be798ef7e502ddee0b9edf30d97e16b6/docs/reviews.md#L238)):*
<details><summary><i>Previously, pkaminski (Piotr Kaminski) wrote…</i></summary><blockquote>

I think you should approach this more from a user's experience point of view, rather than the definitions and algorithms that we think about during implementation.  (We also generally reserve bold text for referencing UI elements or concepts.)  I'd use an approach of what -> why -> how, perhaps along these lines:

> When you publish a review and you have files left to review or discussions left to reply (red counters), the review will be automatically *deferred* for you:  the red counters will turn grey with a red outline and the review will not be awaiting your action.  This lets you post a partial review &mdash; perhaps requesting some larger design changes or putting off reviewing test cases &mdash; and visibly hand off responsibility for taking the next action.
>
> `reviewable deferral dashboard`
>
> A review will remain deferred until either a new revision of a file becomes available for you to review or a new comment is posted.  When this happens, the review will be reactivated for you with all counters going back to being red (including for files or discussions you had deferred), and the review awaiting your action once more.
> 
> Note that you can continue manipulating a review as usual while it's deferred, except that Reviewable won't suggest the next set of diffs to review.  If you wish, you can also reactivate a deferred review manually by clicking the **continue review now** button on the review page.
>
> `reviewable deferral changes`
>
> {:tip}
> Sending an individual comment (via its dedicated send button) doesn't affect deferrals either way:  it will neither defer a review, nor cause a deferred review to become active again.
</blockquote></details>

Done.
___
*[enterprise/changelog.md, line 14 at r1](https://reviewable.io/reviews/reviewable/reviewable/846#-Md_EyEmCcgel6-jVUZL:-MdrGWYm-_ZfAcRm0pCO:b-896fix) ([raw file](https://github.com/reviewable/reviewable/blob/10c8eba2be798ef7e502ddee0b9edf30d97e16b6/enterprise/changelog.md#L14)):*
<details><summary><i>Previously, pkaminski (Piotr Kaminski) wrote…</i></summary><blockquote>

Please don't add this to the changelog until we remove the gating (and hence make the feature available to Enterprise customers).
</blockquote></details>

Done.

**Review by pkaminski — COMMENTED** [review]
> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/reviewable/reviewable/846)* status: all files reviewed, 2 unresolved discussions (waiting on @cgiroux86)

___
*[docs/repositories.md, line 229 at r2](https://reviewable.io/reviews/reviewable/reviewable/846#-MdrjRFgAbXz28D14b0F:-MdrjRFgAbXz28D14b0G:b-ov5fzf) ([raw file](https://github.com/reviewable/reviewable/blob/d4285154ffc621f6dc16d95572db8a86f31c8c72/docs/repositories.md#L229)):*
> ```Markdown
>   ],
>   deferringReviewers: [ // List of reviewers who are deferring and will be removed from pendingReviewers
>   // by default unless your completion condition manipulates pendingReviewers or deferringReviewers
> ```

manipulates -> accesses
___
*[docs/repositories.md, line 300 at r2](https://reviewable.io/reviews/reviewable/reviewable/846#-Mdrjd8j6t5ednJp4LkQ:-Mdrjd8j6t5ednJp4LkR:be9jztc) ([raw file](https://github.com/reviewable/reviewable/blob/d4285154ffc621f6dc16d95572db8a86f31c8c72/docs/repositories.md#L300)):*
> ```Markdown
> 
> #### `pendingReviewers`
> An array of objects with a `username` property listing the users whose attention is needed to advance the review, like `[{username: 'pkaminski'}]`.  The contents of this list will be automatically formatted and appended to the `description` and `shortDescription`.  You can either compute this value from scratch, or crib from the `review.pendingReviewers` input value, which contains Reviewable's guess as to who the pending reviewers should be.  If you don't compute your own `pendingReviewers`, Reviewable will remove any users who are [deferring](reviews.md#deferring-a-review) from the list of `pendingReviewers`.
> ```

That seems backwards?  Isn't it more like "If you compute your own `pendingReviewers` from scratch, Reviewable will remove... unless your code accesses `review.deferredReviewers`".

**Review by cgiroux86 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/reviewable/reviewable/846)* status: 5 of 7 files reviewed, 2 unresolved discussions (waiting on @pkaminski)

___
*[docs/repositories.md, line 229 at r2](https://reviewable.io/reviews/reviewable/reviewable/846#-MdrjRFgAbXz28D14b0F:-MdvcFn90e138cJl3XcF:b-896fix) ([raw file](https://github.com/reviewable/reviewable/blob/d4285154ffc621f6dc16d95572db8a86f31c8c72/docs/repositories.md#L229)):*
<details><summary><i>Previously, pkaminski (Piotr Kaminski) wrote…</i></summary><blockquote>

manipulates -> accesses
</blockquote></details>

Done.
___
*[docs/repositories.md, line 300 at r2](https://reviewable.io/reviews/reviewable/reviewable/846#-Mdrjd8j6t5ednJp4LkQ:-MdvcGvjCgrV_A2glODF:b-896fix) ([raw file](https://github.com/reviewable/reviewable/blob/d4285154ffc621f6dc16d95572db8a86f31c8c72/docs/repositories.md#L300)):*
<details><summary><i>Previously, pkaminski (Piotr Kaminski) wrote…</i></summary><blockquote>

That seems backwards?  Isn't it more like "If you compute your own `pendingReviewers` from scratch, Reviewable will remove... unless your code accesses `review.deferredReviewers`".
</blockquote></details>

Done.

**Review by pkaminski — COMMENTED** [review]
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/reviewable/reviewable/846)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @cgiroux86)

**Pull request merged**
