### PR TITLE
Add documentation for /team_constraints API

### PR DESCRIPTION
**Pull request by snoack**
This change is [Reviewable](https://reviewable.io/reviews/Reviewable/Reviewable/1172)

### CODE REVIEW

**Review by snoack — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Reviewable/Reviewable/1172)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @pkaminski)

___
*[`enterprise/api.md` line 92 at r1](https://reviewable.io/reviews/Reviewable/Reviewable/1172#-O3yat5N4xLlVtIyN38t:-O3yat5N4xLlVtIyN38u:b-qzq16b) ([raw file](https://github.com/Reviewable/Reviewable/blob/7679c30ec8d750213385d0276f61265c82cc0cbb/enterprise/api.md#L92)):*
> ```Markdown
> #### Retrieving seats team constraints
> 
> *Added in server build #xxxx*
> ```

@pkaminski Please let me know what to put here once deployed.

**Review by pkaminski — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Reviewable/Reviewable/1172)* status: all files reviewed, 2 unresolved discussions (waiting on @snoack)

___
*[`enterprise/api.md` line 95 at r1](https://reviewable.io/reviews/Reviewable/Reviewable/1172#-O3ypNbx71JL6NriU6zl:-O3ypNbx71JL6NriU6zm:b-7obgxm) ([raw file](https://github.com/Reviewable/Reviewable/blob/7679c30ec8d750213385d0276f61265c82cc0cbb/enterprise/api.md#L95)):*
> ```Markdown
> 
> The `team_constraints` API endpoint provides a list of teams that this
> Reviewable instance is restricted to in the format `<org name>/<team slug>`.
> ```

Should add a link to https://docs.reviewable.io/subscriptions.html#team-constraints, and perhaps a crosslink from there back to here as well.  (Maybe do the same for the license info API?)

**Review by snoack — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Reviewable/Reviewable/1172)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @pkaminski and @snoack)

___
*[`enterprise/api.md` line 95 at r1](https://reviewable.io/reviews/Reviewable/Reviewable/1172#-O3ypNbx71JL6NriU6zl:-O3z0K9y6eZZTdDrmGL7:b-896fix) ([raw file](https://github.com/Reviewable/Reviewable/blob/7679c30ec8d750213385d0276f61265c82cc0cbb/enterprise/api.md#L95)):*
<details><summary><i>Previously, pkaminski (Piotr Kaminski) wrote…</i></summary><blockquote>

Should add a link to https://docs.reviewable.io/subscriptions.html#team-constraints, and perhaps a crosslink from there back to here as well.  (Maybe do the same for the license info API?)
</blockquote></details>

Done.

**Review by pkaminski — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Reviewable/Reviewable/1172)* status: all files reviewed, 1 unresolved discussion (waiting on @snoack)

**Review by pkaminski — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Reviewable/Reviewable/1172)* status: all files reviewed, 1 unresolved discussion (waiting on @snoack)

**Review by pkaminski — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Reviewable/Reviewable/1172)* status: all files reviewed, 2 unresolved discussions (waiting on @snoack)

___
*[`enterprise/api.md` line 119 at r4](https://reviewable.io/reviews/Reviewable/Reviewable/1172#-O407z2H1_4Xr12ZY0Cu:-O407z2H1_4Xr12ZY0Cv:b-plae4) ([raw file](https://github.com/Reviewable/Reviewable/blob/799f138d5d981096f4df3576b840dd2c89fc2e6c/enterprise/api.md#L119)):*
> ```Markdown
> [team constraints](https://docs.reviewable.io/subscriptions.html#team-constraints).
> The request body is expected to be a JSON-encoded array of strings in the format `<org name>/<team slug>`.
> In order to disable team constraints set it to an empty array or `null` or `undefined`.
> ```

`undefined` is not a valid JSON value.

**Review by snoack — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Reviewable/Reviewable/1172)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @snoack)

___
*[`enterprise/api.md` line 119 at r4](https://reviewable.io/reviews/Reviewable/Reviewable/1172#-O407z2H1_4Xr12ZY0Cu:-O40d97r8pL_1nS-1ZAd:b-896fix) ([raw file](https://github.com/Reviewable/Reviewable/blob/799f138d5d981096f4df3576b840dd2c89fc2e6c/enterprise/api.md#L119)):*
<details><summary><i>Previously, pkaminski (Piotr Kaminski) wrote…</i></summary><blockquote>

`undefined` is not a valid JSON value.
</blockquote></details>

Done.

**Review by pkaminski — COMMENTED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Reviewable/Reviewable/1172)* status: all files reviewed, 1 unresolved discussion (waiting on @snoack)

**Review by snoack — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Reviewable/Reviewable/1172)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @snoack)

___
*[`enterprise/api.md` line 119 at r5](https://reviewable.io/reviews/Reviewable/Reviewable/1172#-O45g6f07cKGVj-E-J-n:-O45g6f07cKGVj-E-J-o:b-sl8rin) ([raw file](https://github.com/Reviewable/Reviewable/blob/3dcb5a5c2ac33d5f320208350c5e3bc5e18c4e18/enterprise/api.md#L119)):*
> ```Markdown
> [team constraints](https://docs.reviewable.io/subscriptions.html#team-constraints).
> The request body is expected to be a JSON-encoded array of strings in the format `<org name>/<team slug>`.
> In order to disable team constraints set it to an empty array or `null`.
> ```

The `express.json` middleware apparently cannot handle `null` as top-level value.

**Review by pkaminski — COMMENTED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Reviewable/Reviewable/1172)* status: all files reviewed, 1 unresolved discussion (waiting on @snoack)

**Review by pkaminski — COMMENTED** [review]
> Reviewed 1 of 1 files at r7.
> Dismissed @snoack from a discussion.
> *[Reviewable](https://reviewable.io/reviews/Reviewable/Reviewable/1172)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @snoack)

___
*[`enterprise/api.md` line 92 at r1](https://reviewable.io/reviews/Reviewable/Reviewable/1172#-O3yat5N4xLlVtIyN38t:-O5kyYwxBVH98qmapFqA:b-bw8e14) ([raw file](https://github.com/Reviewable/Reviewable/blob/7679c30ec8d750213385d0276f61265c82cc0cbb/enterprise/api.md#L92)):*
<details><summary><i>Previously, snoack (Sebastian Noack) wrote…</i></summary><blockquote>

@pkaminski Please let me know what to put here once deployed.
</blockquote></details>

Updated.

**Pull request merged**
