### PR TITLE
Add review summary information to docs.

### PR DESCRIPTION
**Pull request by cgiroux86**
This change is [Reviewable](https://reviewable.io/reviews/reviewable/reviewable/948)

### CODE REVIEW

**Comment by cgiroux86** [comment]
*[`docs/reviews.md` line 273 at r1](https://reviewable.io/reviews/reviewable/reviewable/948#-N8Fih133SKyjzcoia35:-N8Fih14-3HtTGUcbQAf:b-f2my21) ([raw file](https://github.com/reviewable/reviewable/blob/0dd42804b5d7e9606f0f792c213e64d2232217ab/docs/reviews.md#L273)):*
> ```Markdown
> ## Review summary
> 
> When reviewing multiple files simulataneously, Reviewable will provide a **review summary** at the end of the review. The review summary allows you the option to mark all files you're personally responsible for as reviewed and/or mark any discussions left **unread** as **read**. In addition, you can also leave a summary of the review or simply **approve** the review (if allowed), by clicking the `:lgtm:` button on the draft. For more information on using the `:lgtm/approve` functionality, see [the docs](repositories.md#approve-button-output) here. Note any discussions started in the **review summary** will be added to the **top level review discussion**, which is always considered resolved.
> ```

Should I add screenshots or information about the counters and/or their possible states here too? I was trying to keep it as concise as possible.

**Review by pkaminski — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/reviewable/reviewable/948)* status: all files reviewed, 1 unresolved discussion (waiting on @cgiroux86)

___
*[`docs/reviews.md` line 273 at r1](https://reviewable.io/reviews/reviewable/reviewable/948#-N8Fih133SKyjzcoia35:-N8Fiws81gfAvFm1-_tS:bvg8fpq) ([raw file](https://github.com/reviewable/reviewable/blob/0dd42804b5d7e9606f0f792c213e64d2232217ab/docs/reviews.md#L273)):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

Should I add screenshots or information about the counters and/or their possible states here too? I was trying to keep it as concise as possible.
</blockquote></details>

The docs are the right place to aim for completeness, so I'd definitely add a screenshot and maybe expand a bit on when/why the counters are red or not.  Probably worth mentioning that hovering over or touching the counters will reveal the action buttons, since that functionality is a bit hidden.

**Review by pkaminski — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/reviewable/reviewable/948)* status: all files reviewed, 1 unresolved discussion (waiting on @cgiroux86)

___
*[`docs/reviews.md` line 273 at r1](https://reviewable.io/reviews/reviewable/reviewable/948#-N8Fih133SKyjzcoia35:-N8FjtGp9eaT1eg-ieoT:b-bmqute) ([raw file](https://github.com/reviewable/reviewable/blob/0dd42804b5d7e9606f0f792c213e64d2232217ab/docs/reviews.md#L273)):*
<details><summary><i>Previously, pkaminski (Piotr Kaminski) wrote…</i></summary><blockquote>

The docs are the right place to aim for completeness, so I'd definitely add a screenshot and maybe expand a bit on when/why the counters are red or not.  Probably worth mentioning that hovering over or touching the counters will reveal the action buttons, since that functionality is a bit hidden.
</blockquote></details>

I'd also move this up to be a subsection of the "Publishing your review" section.  You can emphasize that the summary is placed at the bottom of the file for convenience, so you don't need to scroll back to the top to leave a comment, or look for the publish button in the toolbar.

Another minor wording tweak:  "When reviewing multiple files simultaneously" doesn't really make sense -- maybe add a "unless the number of files forced the review into displaying one file at a time" at the end of the sentence instead.

**Review by pkaminski — COMMENTED** [review]
> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/reviewable/reviewable/948)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @cgiroux86 and @pkaminski)

**Review by pkaminski — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/reviewable/reviewable/948)* status: all files reviewed, 1 unresolved discussion (waiting on @cgiroux86)

**Review by pkaminski — COMMENTED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/reviewable/reviewable/948)* status: all files reviewed, 1 unresolved discussion (waiting on @cgiroux86)

**Review by cgiroux86 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/reviewable/reviewable/948)* status: 1 of 2 files reviewed, all discussions resolved (waiting on @pkaminski)

___
*[`docs/reviews.md` line 273 at r1](https://reviewable.io/reviews/reviewable/reviewable/948#-N8Fih133SKyjzcoia35:-N8FjlH095p_VWqSmCmn:b-bt0obc) ([raw file](https://github.com/reviewable/reviewable/blob/0dd42804b5d7e9606f0f792c213e64d2232217ab/docs/reviews.md#L273)):*
<details><summary><i>Previously, pkaminski (Piotr Kaminski) wrote…</i></summary><blockquote>

I'd also move this up to be a subsection of the "Publishing your review" section.  You can emphasize that the summary is placed at the bottom of the file for convenience, so you don't need to scroll back to the top to leave a comment, or look for the publish button in the toolbar.

Another minor wording tweak:  "When reviewing multiple files simultaneously" doesn't really make sense -- maybe add a "unless the number of files forced the review into displaying one file at a time" at the end of the sentence instead.
</blockquote></details>

Done. Markdown is hard to read/edit in VSCode! :)

**Comment by cgiroux86** [comment]
*[`docs/reviews.md` line 40 at r6](https://reviewable.io/reviews/reviewable/reviewable/948#-N8FtpqnEDZx1SB6NVAm:-N8FtpqnEDZx1SB6NVAn:b-fo5ddx) ([raw file](https://github.com/reviewable/reviewable/blob/e82bac60160a60a4ec05ea4e76e226a241f550e7/docs/reviews.md#L40)):*
> ```Markdown
> 
> {:.important}
> For convenience (to avoid scrolling back to the top to leave a comment), Reviewable will provide a **review summary** at the end of the review, unless the number of files forced the review into displaying one file at a time. The review summary allows you the option to mark all files you're personally responsible for as reviewed and/or mark any discussions left **unread** as **read**. When these counters are <span class="red label">red</span>, it indicates there's still pending actions for *you* to take, which can be done by hovering or clicking the <span class="red label">red counter</span>. If the counters are grey, it's purely an indication of the review state.
> ```

Should I make note that marking all files reviewed will be at the `last` revision`?

**Review by pkaminski — COMMENTED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/reviewable/reviewable/948)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @cgiroux86)

**Pull request merged**
