### PR TITLE
Update completion condition docs for NodeJS 18.x

### PR DESCRIPTION
**Pull request by fahhem**
This change is [Reviewable](https://reviewable.io/reviews/Reviewable/Reviewable/1016)

### CODE REVIEW

**Review by pkaminski — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Reviewable/Reviewable/1016)* status: all files reviewed, 1 unresolved discussion (waiting on @fahhem)

___
*[`docs/repositories.md` line 178 at r1](https://reviewable.io/reviews/Reviewable/Reviewable/1016#-NPyFzIU6hiB8UeDSbtj:-NPyFzIU6hiB8UeDSbtk:b-ou6h2r) ([raw file](https://github.com/Reviewable/Reviewable/blob/49195f8cd304c28dc5fee6131a9b235af2d96d82/docs/repositories.md#L178)):*
> ```Markdown
> In the **Condition Code** panel, you can edit the code that determines when a review is complete and otherwise tweaks low-level review data.  Simple things are pretty easy to accomplish but you have the power to implement arbitrarily complex logic if you need to.  You can find [a number of examples](https://github.com/Reviewable/Reviewable/tree/master/examples/conditions) in our repository to get you started, and full details follow below.
> 
> The condition code will run in an isolated environment on AWS Lambda, Azure Functions, or in a VM, depending on your deployment. For `https://reviewable.io/` customers, this is AWS Lambda. As of this writing, and this gets updated regularly, deployments against AWS Lambda run in a NodeJS 18.x environment.
> ```

These docs are meant for end users, so I think let's just stick to generic "isolated environment" -- only the admins need to know or care about the specifics, and they can learn about that from the Enterprise config docs.

If you think it's worth saying explicitly that we use Lambda on reviewable.io then perhaps the [Security Concerns](https://docs.reviewable.io/repositories.html#security-concerns) section might be more appropriate (that's one of the few bits of docs aimed more at admins).  I'd definitely leave out anything about Azure or `vm2` as those are Enterprise-only.

**Review by fahhem — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Reviewable/Reviewable/1016)* status: all files reviewed, 1 unresolved discussion (waiting on @pkaminski)

___
*[`docs/repositories.md` line 178 at r1](https://reviewable.io/reviews/Reviewable/Reviewable/1016#-NPyFzIU6hiB8UeDSbtj:-NPyHI1TBGhNBAXSYnrA:b-85f8t9) ([raw file](https://github.com/Reviewable/Reviewable/blob/49195f8cd304c28dc5fee6131a9b235af2d96d82/docs/repositories.md#L178)):*
<details><summary><i>Previously, pkaminski (Piotr Kaminski) wrote…</i></summary><blockquote>

These docs are meant for end users, so I think let's just stick to generic "isolated environment" -- only the admins need to know or care about the specifics, and they can learn about that from the Enterprise config docs.

If you think it's worth saying explicitly that we use Lambda on reviewable.io then perhaps the [Security Concerns](https://docs.reviewable.io/repositories.html#security-concerns) section might be more appropriate (that's one of the few bits of docs aimed more at admins).  I'd definitely leave out anything about Azure or `vm2` as those are Enterprise-only.
</blockquote></details>

Are these docs not used by Enterprise customers as well?

**Review by pkaminski — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Reviewable/Reviewable/1016)* status: all files reviewed, 1 unresolved discussion (waiting on @fahhem)

___
*[`docs/repositories.md` line 178 at r1](https://reviewable.io/reviews/Reviewable/Reviewable/1016#-NPyFzIU6hiB8UeDSbtj:-NPyZSFICFL4h1SYrWBc:b10bxzn) ([raw file](https://github.com/Reviewable/Reviewable/blob/49195f8cd304c28dc5fee6131a9b235af2d96d82/docs/repositories.md#L178)):*
<details><summary><i>Previously, fahhem (Fahrzin Hemmati) wrote…</i></summary><blockquote>

Are these docs not used by Enterprise customers as well?
</blockquote></details>

Yes, but still targeted at users rather than admins.  For Enterprise admins putting stuff in the Enterprise config or security docs would be more appropriate.

**Review by fahhem — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Reviewable/Reviewable/1016)* status: all files reviewed, 1 unresolved discussion (waiting on @pkaminski)

___
*[`docs/repositories.md` line 178 at r1](https://reviewable.io/reviews/Reviewable/Reviewable/1016#-NPyFzIU6hiB8UeDSbtj:-NPy_3cN4suEgaRzC5nH:b-c8j2xf) ([raw file](https://github.com/Reviewable/Reviewable/blob/49195f8cd304c28dc5fee6131a9b235af2d96d82/docs/repositories.md#L178)):*
<details><summary><i>Previously, pkaminski (Piotr Kaminski) wrote…</i></summary><blockquote>

Yes, but still targeted at users rather than admins.  For Enterprise admins putting stuff in the Enterprise config or security docs would be more appropriate.
</blockquote></details>

This whole section is only relevant to admins though, right?

**Review by pkaminski — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Reviewable/Reviewable/1016)* status: all files reviewed, 1 unresolved discussion (waiting on @fahhem)

___
*[`docs/repositories.md` line 178 at r1](https://reviewable.io/reviews/Reviewable/Reviewable/1016#-NPyFzIU6hiB8UeDSbtj:-NPy_IDm4yOXYhGLTfGY:bc3pm8d) ([raw file](https://github.com/Reviewable/Reviewable/blob/49195f8cd304c28dc5fee6131a9b235af2d96d82/docs/repositories.md#L178)):*
<details><summary><i>Previously, fahhem (Fahrzin Hemmati) wrote…</i></summary><blockquote>

This whole section is only relevant to admins though, right?
</blockquote></details>

Sorry, "admin" is overloaded and I wasn't clear on my intended meaning.  This section is relevant to end users, which I consider to include repo admins.  The details of how conditions are executed are only relevant to instance admins / IT admins, a much more rarified breed.  They sometimes overlap with repo admins but definitely not always or even mostly.

**Review by fahhem — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Reviewable/Reviewable/1016)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @pkaminski)

___
*[`docs/repositories.md` line 178 at r1](https://reviewable.io/reviews/Reviewable/Reviewable/1016#-NPyFzIU6hiB8UeDSbtj:-NQVnaFZ6Yl_sWSAds4a:b-9v7tf) ([raw file](https://github.com/Reviewable/Reviewable/blob/49195f8cd304c28dc5fee6131a9b235af2d96d82/docs/repositories.md#L178)):*
<details><summary><i>Previously, pkaminski (Piotr Kaminski) wrote…</i></summary><blockquote>

Sorry, "admin" is overloaded and I wasn't clear on my intended meaning.  This section is relevant to end users, which I consider to include repo admins.  The details of how conditions are executed are only relevant to instance admins / IT admins, a much more rarified breed.  They sometimes overlap with repo admins but definitely not always or even mostly.
</blockquote></details>

Done.

I also split the paragraph on sentences, which IMO makes the text more readable than really long lines that require wrapping, but I can undo that if you prefer it this way

**Review by pkaminski — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Reviewable/Reviewable/1016#-:-NQWLNoZ8nCEBy09u_xw:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @fahhem)

___
*[`docs/repositories.md` line 178 at r1](https://reviewable.io/reviews/Reviewable/Reviewable/1016#-NPyFzIU6hiB8UeDSbtj:-NQWKxKuB1WF1i7z6_Wk:b-18sq9u) ([raw file](https://github.com/Reviewable/Reviewable/blob/49195f8cd304c28dc5fee6131a9b235af2d96d82/docs/repositories.md#L178)):*
<details><summary><i>Previously, fahhem (Fahrzin Hemmati) wrote…</i></summary><blockquote>

Done.

I also split the paragraph on sentences, which IMO makes the text more readable than really long lines that require wrapping, but I can undo that if you prefer it this way
</blockquote></details>

LGTM.  No strong opinion on line splitting in Markdown text.  I mostly don't split to avoid having to manually re-wrap as I edit (though that's a single keypress away, so it's not super onerous).  It does make diffs harder to read, though, which would be fixed by reviewable/reviewable#848.

**Pull request merged**
