### PR TITLE
Support Lodash 4.x

### PR DESCRIPTION
**Pull request by cgiroux86**
Update docs with information about Lodash 4.x support

---
This change is [Reviewable](https://reviewable.io/reviews/reviewable/reviewable/867)

### CODE REVIEW

**Review by cgiroux86 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/reviewable/reviewable/867)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @pkaminski)

*[a discussion](https://reviewable.io/reviews/reviewable/reviewable/867#-Mj59ANG6JNFKlQwrCxv:-Mj59ANHBwRPh7jB3Mgd:bt2yrbp) (no related file):*
Headway post is drafted -- would appreciate a review when you have a chance :) 

---

**Review by pkaminski — COMMENTED** [review]
> Reviewed 2 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/reviewable/reviewable/867)* status: all files reviewed, 4 unresolved discussions (waiting on @cgiroux86 and @pkaminski)

___
*[docs/repositories.md, line 157 at r2](https://reviewable.io/reviews/reviewable/reviewable/867#-Mj61979EwAm-CG9llQT:-Mj61979EwAm-CG9llQU:b-7ycxvm) ([raw file](https://github.com/reviewable/reviewable/blob/f13ac2e733bf17c61c590a69714779afde84ff29/docs/repositories.md#L157)):*
> ```Markdown
> In the **Condition Code** panel, you can edit the code that determines when a review is complete.  It starts off with the code that Reviewable uses by default and you can pick other sample conditions to customize or study from the small **Examples** menu above the editor.
> 
> The condition code will run in an isolated NodeJS 14.x environment (as of this writing — this gets updated regularly) that includes the 3.x `lodash` module available through the customary `_` binding. If you'd like to use the newer `lodash` version (4.x at the time of writing), you can do so by setting a **dependencies** flag _anywhere_ in your condition code (see screenshot below for the format to use when flagging the version).  Note Reviewable will default to using Lodash 3.x for existing conditions or if no flag is set.  If you're running Reviewable Enterprise, please don't advertise 4.x support until you're confident you won't need to roll back to avoid your conditions running against the older 3.x version. You can require other built-in Node modules, though some may be disallowed. Each invocation of your code must return a result within three seconds.
> ```

The Enterprise note should just go in the changelog.  Also, if we're going to give an example, it should be in text so that it's copy-pastable.  And I think we should switch to defaulting to Lodash 4.x before we advertise this feature at all, so might as well rewrite with that in mind.
___
*[docs/images/dependencies.png, line 0 at r2](https://reviewable.io/reviews/reviewable/reviewable/867#-Mj60ozq55Upm3f4slVV:-Mj60ozq55Upm3f4slVW:b2g307j) ([raw file](https://github.com/reviewable/reviewable/blob/f13ac2e733bf17c61c590a69714779afde84ff29/docs/images/dependencies.png#L0)):*
Weird, GitHub doesn't render the image in their diff.  You're sure the image file is good?
___
*[enterprise/changelog.md, line 11 at r2](https://reviewable.io/reviews/reviewable/reviewable/867#-Mj61dPj66g0a_qqzebT:-Mj61dPj66g0a_qqzebU:blsk4at) ([raw file](https://github.com/reviewable/reviewable/blob/f13ac2e733bf17c61c590a69714779afde84ff29/enterprise/changelog.md#L11)):*
> ```Markdown
> #### Upcoming changes (min 3107.4890 GHE 2.17+ or 3.0+)
> - Upd: show revision timestamps in the local timezone in the Commits virtual file.
> - Upd: support Lodash 4.x in custom completion conditions.  See [the docs](https://docs.reviewable.io/repositories#custom-review-completion-condition) for more details.
> ```

Add warning about when to advertise this feature here.

**Review by cgiroux86 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/reviewable/reviewable/867)* status: 0 of 3 files reviewed, 4 unresolved discussions (waiting on @pkaminski)

___
*[docs/repositories.md, line 157 at r2](https://reviewable.io/reviews/reviewable/reviewable/867#-Mj61979EwAm-CG9llQT:-MjAz8-CBjp1ZnxCu07Z:b-896fix) ([raw file](https://github.com/reviewable/reviewable/blob/f13ac2e733bf17c61c590a69714779afde84ff29/docs/repositories.md#L157)):*
<details><summary><i>Previously, pkaminski (Piotr Kaminski) wrote…</i></summary><blockquote>

The Enterprise note should just go in the changelog.  Also, if we're going to give an example, it should be in text so that it's copy-pastable.  And I think we should switch to defaulting to Lodash 4.x before we advertise this feature at all, so might as well rewrite with that in mind.
</blockquote></details>

Done.
___
*[enterprise/changelog.md, line 11 at r2](https://reviewable.io/reviews/reviewable/reviewable/867#-Mj61dPj66g0a_qqzebT:-MjB-A9bE3q4D5F_6ELn:b-896fix) ([raw file](https://github.com/reviewable/reviewable/blob/f13ac2e733bf17c61c590a69714779afde84ff29/enterprise/changelog.md#L11)):*
<details><summary><i>Previously, pkaminski (Piotr Kaminski) wrote…</i></summary><blockquote>

Add warning about when to advertise this feature here.
</blockquote></details>

Done.
___
*[docs/images/dependencies.png, line  at r2](https://reviewable.io/reviews/reviewable/reviewable/867#-Mj60ozq55Upm3f4slVV:-MjAyvJnBtBdk4rg6T9a:b-l5def1) ([raw file](https://github.com/reviewable/reviewable/blob/f13ac2e733bf17c61c590a69714779afde84ff29/docs/images/dependencies.png#L)):*
<details><summary><i>Previously, pkaminski (Piotr Kaminski) wrote…</i></summary><blockquote>

Weird, GitHub doesn't render the image in their diff.  You're sure the image file is good?
</blockquote></details>

That's weird -- I wonder if it's a bug on our end?  Everything displayed properly when I previewed it.

**Review by pkaminski — COMMENTED** [review]
> Reviewed 1 of 3 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/reviewable/reviewable/867)* status: all files reviewed, 2 unresolved discussions (waiting on @cgiroux86 and @pkaminski)

___
*[docs/repositories.md, line 159 at r4](https://reviewable.io/reviews/reviewable/reviewable/867#-MjB2VJq9lFRRG0G2KP2:-MjB2VJq9lFRRG0G2KP3:bg9kr2u) ([raw file](https://github.com/reviewable/reviewable/blob/39f33e57f6539107f2968619ba0b0e847fc07c62/docs/repositories.md#L159)):*
> ```Markdown
> The condition code will run in an isolated NodeJS 14.x environment (as of this writing — this gets updated regularly) that includes the 4.x `lodash` module available through the customary `_`.  Note the `lodash` version was updated to `4.x` on **9/9/2021**, so if you have a condition written before the update it will still use the `lodash` 3.x module.  You can update existing conditions to use `lodash` 4.x  by inserting a commmented **dependencies** flag anywhere in your condition code (see snippet below for format). You can require other built-in Node modules, though some may be disallowed. Each invocation of your code must return a result within three seconds.
> 
> ```// dependencies: lodash4```
> ```

I think you can just inline this.  :)  Also, it might make sense to take the entire note out into a `{:.tip}` instead.
___
*[docs/images/dependencies.png, line  at r2](https://reviewable.io/reviews/reviewable/reviewable/867#-Mj60ozq55Upm3f4slVV:-MjB2zQQEzat2sFpu1oD:b-2ut3fq) ([raw file](https://github.com/reviewable/reviewable/blob/f13ac2e733bf17c61c590a69714779afde84ff29/docs/images/dependencies.png#L)):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

That's weird -- I wonder if it's a bug on our end?  Everything displayed properly when I previewed it.
</blockquote></details>

Nah, this is literally the GitHub web UI -- we just link to it.  Oh well, weird.

**Review by cgiroux86 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/reviewable/reviewable/867)* status: 1 of 3 files reviewed, 2 unresolved discussions (waiting on @pkaminski)

___
*[docs/repositories.md, line 159 at r4](https://reviewable.io/reviews/reviewable/reviewable/867#-MjB2VJq9lFRRG0G2KP2:-MjUOPMGDnsWgIAu4E_z:b-896fix) ([raw file](https://github.com/reviewable/reviewable/blob/39f33e57f6539107f2968619ba0b0e847fc07c62/docs/repositories.md#L159)):*
<details><summary><i>Previously, pkaminski (Piotr Kaminski) wrote…</i></summary><blockquote>

I think you can just inline this.  :)  Also, it might make sense to take the entire note out into a `{:.tip}` instead.
</blockquote></details>

Done.

**Review by pkaminski — COMMENTED** [review]
> Reviewed 1 of 2 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/reviewable/reviewable/867)* status: all files reviewed, 1 unresolved discussion (waiting on @pkaminski)

**Review by pkaminski — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/reviewable/reviewable/867)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @cgiroux86)

*[a discussion](https://reviewable.io/reviews/reviewable/reviewable/867#-Mj59ANG6JNFKlQwrCxv:-MjWII98BJewtSkqJvZm:b-z2mjfi) (no related file):*
<details><summary><i>Previously, cgiroux86 (Chris Giroux) wrote…</i></summary><blockquote>

Headway post is drafted -- would appreciate a review when you have a chance :) 
</blockquote></details>

Headway post reviewed and shortened a bit, otherwise looks OK.  Once we add the dependency version display to the client it might be a good idea to mention that in the post and have a screenshot, so they'll know how to confirm which version is actually being used.

---

**Pull request merged**
