### PR TITLE
Add careers page

### PR DESCRIPTION
**Pull request by earlAchromatic**
FYI mdbook doesn't let you render any pages from markdown that aren't in SUMMARY.md. So it has to be on the sidebar unless you know of a workaround...

I put the message about opening a PR in the repo at the bottom to make it slightly less obvious that this is an option. Sort of like a hidden opportunity for those with keen eyes. Figured you might have inputs on all of this so fire away!

- - -
This change is [Reviewable](https://reviewable.io/reviews/reviewable/reviewable/951)

### CODE REVIEW

**Review by pkaminski — COMMENTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/reviewable/reviewable/951)* status: all files reviewed, 1 unresolved discussion (waiting on @earlAchromatic)

*[a discussion](https://reviewable.io/reviews/reviewable/reviewable/951#-N9J26OcDVGHqYb0bS4b:-N9J26OcDVGHqYb0bS4c:bp2y2jl) (no related file):*
I'd leave this out of the docs and just stick it into a new `/careers` directory as `README.md`, with each open position in a separate file (and indexed via the README).  The styling can be inlined into the README as well.

___

**Comment by earlAchromatic** [comment]
<details><summary><i>Previously, pkaminski (Piotr Kaminski) wrote…</i></summary><blockquote>

I'd leave this out of the docs and just stick it into a new `/careers` directory as `README.md`, with each open position in a separate file (and indexed via the README).  The styling can be inlined into the README as well.
</blockquote></details>

Ah well apparently you [can't use inline styles in GitHub markdown](https://github.com/orgs/community/discussions/22728) so I just left them out.

**Review by pkaminski — COMMENTED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/reviewable/reviewable/951)* status: all files reviewed, 1 unresolved discussion (waiting on @earlAchromatic)

___
*[`careers/README.md` line 12 at r2](https://reviewable.io/reviews/reviewable/reviewable/951#-N9trVdQ1cbPrsSVdhCs:-N9trVdQ1cbPrsSVdhCt:bk0k44d) ([raw file](https://github.com/reviewable/reviewable/blob/f4a3aba7d77a6f8a813f18014b6d50bd5487955c/careers/README.md#L12)):*
> ```Markdown
> <hr/>
> 
> <p align="center">...but if you are feeling inspired, feel free to open a PR in this repository to tell us about yourself.</p>
> ```

How about phrasing this a bit more subtly, like "...but if you're feeling inspired, we do accept PRs against this repo!  :wink: "

Also, you can try using `<sup>` to at least make the font smaller, even if we can't mess with the color.

**Review by earlAchromatic — COMMENTED** [review]
Sorry it took so long I had to go through and delete all **40** empty comments I had started on this review the other night... ha!

> *[Reviewable](https://reviewable.io/reviews/reviewable/reviewable/951#-:-NA1j994EDtS34vXv1dD:bxmucmz)* status: 2 of 3 files reviewed, all discussions resolved (waiting on @pkaminski)

**Review by pkaminski — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/reviewable/reviewable/951)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @earlAchromatic)

**Pull request merged**
