### PR TITLE
Document `github-status.creator` setting.

### PR DESCRIPTION
**Pull request by pkaminski**
Viz https://github.com/Reviewable/reviewable-server/pull/665

- - -
This change is [Reviewable](https://reviewable.io/reviews/Reviewable/Reviewable/1207)

### CODE REVIEW

**Review by snoack — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Reviewable/Reviewable/1207)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @pkaminski)

___
*[`examples/settings/settings.yaml` line 49 at r1](https://reviewable.io/reviews/Reviewable/Reviewable/1207#-ODRnQszCk7o7fs01Ua8:-ODRnQszCk7o7fs01Ua9:blkijhh) ([raw file](https://github.com/Reviewable/Reviewable/blob/5a9a602cfaa7d72a95adb6be5cd5ee685fb5dd66/examples/settings/settings.yaml#L49)):*
> ```YAML
>   updates: always
>   # `author` is the username of the account used to post the status. Requires the repository to
>   # belong to an organization and the user specified as `commenter` to be a member of that
> ```

You copied `commenter` which is called `author` here.

**Review by pkaminski — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Reviewable/Reviewable/1207)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @snoack)

___
*[`examples/settings/settings.yaml` line 49 at r1](https://reviewable.io/reviews/Reviewable/Reviewable/1207#-ODRnQszCk7o7fs01Ua8:-ODSLKq0-opQYXl533fI:b-896fix) ([raw file](https://github.com/Reviewable/Reviewable/blob/5a9a602cfaa7d72a95adb6be5cd5ee685fb5dd66/examples/settings/settings.yaml#L49)):*
<details><summary><i>Previously, snoack (Sebastian Noack) wrote…</i></summary><blockquote>

You copied `commenter` which is called `author` here.
</blockquote></details>

Done.

**Review by snoack — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/Reviewable/Reviewable/1207#-:-ODSMSPU2Mfe7SPBAcor:bnfp4nl)* status: 0 of 2 files reviewed, all discussions resolved

**Review by snoack — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Reviewable/Reviewable/1207)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @pkaminski)

**Pull request merged**
