### PR TITLE
Terms update

### PR DESCRIPTION
**Pull request by pkaminski**
This change is [Reviewable](https://reviewable.io/reviews/Reviewable/Reviewable/1120)

### CODE REVIEW

**Review by fahhem — COMMENTED** [review]
> Reviewed 1 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/Reviewable/Reviewable/1120)* status: 1 of 4 files reviewed, 3 unresolved discussions (waiting on @pkaminski and @snoack)

___
*[`legal/acceptable_use.md` line 99 at r3](https://reviewable.io/reviews/Reviewable/Reviewable/1120#-NigO0cZEcmgELKyX5Fr:-NigO0cZEcmgELKyX5Fs:bvnuwbt) ([raw file](https://github.com/Reviewable/Reviewable/blob/bcf4d6405cc71930c9933ff76b4a793f7006d595/legal/acceptable_use.md#L99)):*
> ```Markdown
> **Enforcement.** Reviewable retains full discretion to take action in response to a violation of these policies, including account suspension, account termination, or removal of content.
> 
> **Reinstatement and appeal.** If your content or account has been disabled or restricted and you seek reinstatement or wish to appeal, please [get in touch](mailto:legal@reviewable.io).
> ```

since we don't provide a means of flagging/reporting, I assume most of this is toothless unless something really hits the fan (and that doesn't get removed from GitHub by them)?
___
*[`legal/terms.md` line 188 at r3](https://reviewable.io/reviews/Reviewable/Reviewable/1120#-NigOsf-9WaLeKRR59UF:-NigOsf-9WaLeKRR59UG:bd99x1f) ([raw file](https://github.com/Reviewable/Reviewable/blob/bcf4d6405cc71930c9933ff76b4a793f7006d595/legal/terms.md#L188)):*
> ```Markdown
> 
> ### 3. Billing Schedule; No Refunds
> **Payment Based on Plan** For monthly or yearly payment plans, the Service is billed in advance on a monthly or yearly basis respectively and is non-refundable. There will be no refunds for partial months of service, downgrade refunds, or refunds for months unused with an open Account; however, the service will remain active for the length of the paid billing period. In order to treat everyone equally, no exceptions will be made.
> ```

This doesn't mention seats, contributors, or anything like that. Should it or is this what GitHub uses despite also being seat based?
___
*[`legal/terms.md` line 192 at r3](https://reviewable.io/reviews/Reviewable/Reviewable/1120#-NigP6S-BLhW_ccL78Lh:-NigP6S-BLhW_ccL78Li:bq5310v) ([raw file](https://github.com/Reviewable/Reviewable/blob/bcf4d6405cc71930c9933ff76b4a793f7006d595/legal/terms.md#L192)):*
> ```Markdown
> **Payment Based on Usage** Some Service features are billed based on your usage. A limited quantity of these Service features may be included in your plan for a limited term without additional charge. If you choose to purchase paid Service features beyond the quantity included in your plan, you pay for those Service features based on your actual usage in the preceding month. Monthly payment for these purchases will be charged on a periodic basis in arrears. See [Reviewable Additional Product Terms for Details](additional_product_terms.md).
> 
> **Invoicing** For invoiced Users, User agrees to pay the fees in full, up front without deduction or setoff of any kind, in U.S. Dollars. User must pay the fees within thirty (30) days of the Reviewable invoice date. Amounts payable under this Agreement are non-refundable, except as otherwise provided in this Agreement. If User fails to pay any fees on time, Reviewable reserves the right, in addition to taking any other action at law or equity, to (i) charge interest on past due amounts at 1.0% per month or the highest interest rate allowed by law, whichever is less, and to charge all expenses of recovery, and (ii) terminate the applicable order form. User is solely responsible for all taxes, fees, duties and governmental assessments (except for taxes based on Reviewable's net income) that are imposed or become due in connection with this Agreement.
> ```

"must ay the fees within thirty (30) days" unless otherwise stated on the invoice.

This is because we have some customers we explicitly do net 60 for, like XM Cyber, since they can't pay us faster than 30 days even if they really wanted to

**Review by pkaminski — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Reviewable/Reviewable/1120)* status: 1 of 4 files reviewed, 2 unresolved discussions (waiting on @fahhem and @snoack)

___
*[`legal/acceptable_use.md` line 99 at r3](https://reviewable.io/reviews/Reviewable/Reviewable/1120#-NigO0cZEcmgELKyX5Fr:-NigROJZAVSWcEHOLU-u:b-r7wjc0) ([raw file](https://github.com/Reviewable/Reviewable/blob/bcf4d6405cc71930c9933ff76b4a793f7006d595/legal/acceptable_use.md#L99)):*
<details><summary><i>Previously, fahhem (Fahrzin Hemmati) wrote…</i></summary><blockquote>

since we don't provide a means of flagging/reporting, I assume most of this is toothless unless something really hits the fan (and that doesn't get removed from GitHub by them)?
</blockquote></details>

Yeah, it's really just a failsafe:  _if_ we somehow decided to disable an account independently of GitHub (unlikely), _and_ the user somehow wasn't aware of it (even less likely), _and_ they wanted to appeal, then at least we have a stated way to get the process started.
___
*[`legal/terms.md` line 188 at r3](https://reviewable.io/reviews/Reviewable/Reviewable/1120#-NigOsf-9WaLeKRR59UF:-NigWEYq6L7ub98rzSMO:b-zaggy6) ([raw file](https://github.com/Reviewable/Reviewable/blob/bcf4d6405cc71930c9933ff76b4a793f7006d595/legal/terms.md#L188)):*
<details><summary><i>Previously, fahhem (Fahrzin Hemmati) wrote…</i></summary><blockquote>

This doesn't mention seats, contributors, or anything like that. Should it or is this what GitHub uses despite also being seat based?
</blockquote></details>

This is what GitHub uses, so I assume the extra detail isn't needed.  I believe changes in the number of seats fall under the more general "downgrade / upgrade".
___
*[`legal/terms.md` line 192 at r3](https://reviewable.io/reviews/Reviewable/Reviewable/1120#-NigP6S-BLhW_ccL78Lh:-NigWW-W55AR_XuTfviE:b-rp1b2i) ([raw file](https://github.com/Reviewable/Reviewable/blob/bcf4d6405cc71930c9933ff76b4a793f7006d595/legal/terms.md#L192)):*
<details><summary><i>Previously, fahhem (Fahrzin Hemmati) wrote…</i></summary><blockquote>

"must ay the fees within thirty (30) days" unless otherwise stated on the invoice.

This is because we have some customers we explicitly do net 60 for, like XM Cyber, since they can't pay us faster than 30 days even if they really wanted to
</blockquote></details>

This is only for SaaS, i.e., Business tier customers who opt into invoicing.  I think it's fair to require 30 days net in that case, since otherwise they'd be doing "0 days net" via a card anyway.  If a customer needs different terms then it's Enterprise for them!  (Or an informal agreement to let things slide, since we're not required to enforce this.)

**Review by AmircaBladis — COMMENTED** [review]
> Reviewed 1 of 4 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Reviewable/Reviewable/1120)* status: 3 of 4 files reviewed, all discussions resolved (waiting on @snoack)

**Review by snoack — COMMENTED** [review]
:lgtm: (for J. Payment section)

> Reviewed 3 of 4 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Reviewable/Reviewable/1120#-:-Njiv149DOiKv0NV3yFC:b-juer06)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @pkaminski)

**Review by pkaminski — COMMENTED** [review]
> Reviewed 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Reviewable/Reviewable/1120)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @pkaminski)

**Pull request merged**
